### PR TITLE
FIT: FDD, FT0 and FV0 directories are moved into FIT

### PR DESCRIPTION
**Pull request by afurs**
First stage for FIT refactoring

### CODE REVIEW

**Comment by knopers8** [comment]
Which one do we merge first, this or https://github.com/AliceO2Group/QualityControl/pull/1673? there is going to be a merge conflict.

**Comment by afurs** [comment]
Hello @knopers8 please merge #1673, I'll rebase mine PR

**Comment by Barthelemy** [comment]
@TimoWilken @costing The mac check keeps failing on all our PRs: `455/455 Test  #97: CcdbApi-MultiHandle ..................................................................***Timeout 1500.04 sec`

**Comment by knopers8** [comment]
> Hello @knopers8 please merge #1673, I'll rebase mine PR

OK good, as soon as someone from FIT approves and checks are green.

**Comment by afurs** [comment]
Hi @knopers8 could you please merge this PR. Looks like that #1673 is delayed.

**Comment by Barthelemy** [comment]
yes, I will but could you fix the merge conflicts ? thank you

**Comment by afurs** [comment]
> yes, I will but could you fix the merge conflicts ? thank you

conflicts with PR1673?

**Comment by Barthelemy** [comment]
the conflicts with master (listed just below my comment).

**Comment by afurs** [comment]
> the conflicts with master (listed just below my comment).

Ah, there was merged modifications after I uploaded this PR... Ok, I see. I'll fix it.

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
