### PR TITLE
ITS Thr task bug fix + removal of unused stuff

### PR DESCRIPTION
**Pull request by iravasen**

### CODE REVIEW

**Comment by iravasen** [comment]
@knopers8 I have to set `active: "false"` in the json to solve my backpressure issue. Do you know what this does? I cannot figure it out from the code.

**Comment by iravasen** [comment]
@Barthelemy solved, you can force-push at any moment. Sorry the macOS test is again failing.

**Comment by knopers8** [comment]
hi, it disables the sampling policy, i would be rather surprised if you see any data in your QC with `active : false`

**Comment by iravasen** [comment]
This was also my suspect by I managed to have data in QC with active = false. Let me retry to be sure.

**Comment by iravasen** [comment]
yes I do confirm that I see data in the QC plots. This the json I'm using (copying the relevant part only):
```
    "tasks" : {
      "ITSThresholdCalibrationTask-prova" : {
        "active" : "true",
        "className" : "o2::quality_control_modules::its::ITSThresholdCalibrationTask",
        "moduleName" : "QcITS",
        "detectorName" : "ITS",
        "cycleDurationSeconds" : "60",
        "maxNumberCycles" : "-1",
        "dataSource_comment" : "The other type of dataSource is \"direct\", see basic-no-sampling.json.",
        "dataSource" : {
          "type" : "dataSamplingPolicy",
          "name" : "thrcal"
        },
        "location" : "remote",
        "taskParameters" : {}
      }
    }



 },

         "dataSamplingPolicies" : [
           {
             "id" : "thrcal",
             "active" : "false",
             "machines" : [],
             "query" : "tunestring:ITS/TSTR;chipdonestring:ITS/QCSTR;scantype:ITS/SCANT",
             "samplingConditions" : [
               {
                 "condition" : "random",
                 "fraction" : "1",
                 "seed" : "1441"
               }
             ],

             "blocking" : "false"
           }
         ]
```
The output of my test is: http://ccdb-test.cern.ch:8080/browse/qc/ITS/MO/ITSThresholdCalibrationTask-prova/ChipDoneML

**Comment by iravasen** [comment]
Few days ago I tried multiple times with `active = false` but now I can reproduce the same effect even with `active = true` so I was just lucky. I put again active = true. Then this PR is ready for me. I will test in a second moment the code by Giulio

**Review by knopers8 — APPROVED** [review]

**Pull request merged**
