### PR TITLE
Align to O2 updates in TOF

### PR DESCRIPTION
**Pull request by preghenella**
This PR is needed to align the TOF `QualityControl` code to the changes in the decoding API provided by the `o2` .

Now, the issue is that the `o2` PR is failing checks because of a build error in `QualityControl`.
https://github.com/AliceO2Group/AliceO2/pull/3404

I imagine that this PR will also fail because the changes need the `o2` PR to be merged.
I hope this situation can be solved somehow.
@ktf suggested that both PR could be merged at the same time, but I don't know how technically this can be done with all checks passed

### CODE REVIEW

**Comment by preghenella** [comment]
Hello @Barthelemy ,
I opened this PR yesterday (16 hours ago), but it seems like the checks are still pending.
Does it take long before the checks are processed, or is there something not ok?
Thanks,
Roberto

**Comment by ktf** [comment]
You are a first time contributor. You need a review as explained at:

https://aliceo2group.github.io/quickstart/devel.html#pull-request-flow

**Comment by ktf** [comment]
I also invited you to the org, so that you should not have the issue with any other repository.

**Comment by preghenella** [comment]
Thanks @ktf ,
the checks did process and as expected they failed because of the open PR on the `o2`.
This is a bit of a dog chasing its tail.
This PR fails because the PR in the `o2` is still not merged
https://github.com/AliceO2Group/AliceO2/pull/3404
And the PR in the `o2` is failing because of this PR is still not merged.

@ktf , you were saying that we can solve this impasse by merging them both simultaneously.
It is surely fine with me.

Thanks for letting me know if something else has to be done.

**Comment by preghenella** [comment]
Hello @Barthelemy and @ktf ,
do you have any suggestions how to proceed with this PR?
Thanks,
Roberto

**Comment by Barthelemy** [comment]
@preghenella We need to force merge both at the same time. @ktf has the rights to do it, I can only do the one in QC. 
The only other way would be to have the code compatible with both version, possibly with some precompiler instructions. That is not the nicest either.

**Comment by preghenella** [comment]
ok, thanks @Barthelemy .
Let me try to see if I can modify the API on the `o2` side such that it will not cause compilation failures on the `QualityControl` side.

**Comment by Barthelemy** [comment]
@preghenella As you prefer, I don't mind merging both at the same time but I cannot do it on the O2 side.

**Comment by Barthelemy** [comment]
Let's just wait for the O2 PR merge and then we merge this one if it goes through. thanks for the changes.

**Comment by Barthelemy** [comment]
@preghenella could you edit a file to force the rebuild ?

**Comment by preghenella** [comment]
hello @Barthelemy ,
thanks for the patience. The PR in the `o2` is merged.
I close and reopen to start the checks from scratch.

**Comment by Barthelemy** [comment]
good, thanks !

**Comment by preghenella** [comment]
`build/QualityControl/o2` seems to fail because of an unrelated issue
```
305/305 Test  #69: CCDB/test/testCcdbApi.cxx ......................................................***Failed    7.41 sec
```

**Comment by Barthelemy** [comment]
Indeed, sorry about that, we are fixing it. There was a change in the CCDB itself. I will force merge this PR as the change itself built fine.

**Comment by Barthelemy** [comment]
@preghenella could you fix the 2 warnings ? commenting out the name of the arguments `errors` should be enough.

**Comment by preghenella** [comment]
Hi @Barthelemy , ok
I cannot see the details from the CI (ali-ci.cern.ch refused to connect) but I think I understand what you mean (unused variables, I guess).
Roberto

**Comment by preghenella** [comment]
hello @Barthelemy ,
on test is still pending and one failed, but I don't see from the logs what is the cause of the failure.

**Comment by Barthelemy** [comment]
I am also puzzled. @ktf @MichaelLettrich @pzhristov Any idea ?

**Comment by ktf** [comment]
As I wrote somewhere else, I am on it.

**Comment by ktf** [comment]
The pending test should be resolved soon. The other I think I know what (which PR) is causing it, but I am not sure why.

**Pull request merged**
