### PR TITLE
MCH: added FEC synchronization diagnostics

### PR DESCRIPTION
**Pull request by aferrero2707**
This PR adds some diagnostics plots to asses the time synchronization of the individual FEC boards.
The diagnostics is based on the analysis of the heart-beat packet's time stamp.
The following plots are added:
- distribution of heart-beat packet bunch-crossing values for each FEC board (coarse and fine-grained around the expected BC value)
- fraction of out-of-sync FEC boards for each detection element and each chamber, based on the analysis of the HB packet bunch-crossings
- sync status of each FEC board (OK, out-of-synch, missing good HB)

### CODE REVIEW

**Comment by aferrero2707** [comment]
@aphecetche could you have a look? Thanks!

**Comment by Barthelemy** [comment]
@aferrero2707  @aphecetche  
should this be merged or reviewed  ?

**Comment by knopers8** [comment]
@aferrero2707 @aphecetche should we merge it? it's green.

**Comment by aferrero2707** [comment]
@knopers8 yes, it can be merged. Thanks!

**Review by knopers8 — APPROVED** [review]

**Pull request merged**
