### PR TITLE
Fix ccdb json retrieval and test 

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by knopers8** [comment]
The problem in the `o2-dataflow` is quite unexpected and unrelated:
```
-- [ ] [ ] [E] GPU/TPCFastTransformation/macro/loadlibs.C
-- [ ] [ ] [E] GPU/TPCFastTransformation/macro/moveTPCFastTransform.C
-- [ ] [ ] [E] Generators/share/egconfig/pythia8_userhooks_charm.C
CMake Error at cmake/O2ReportNonTestedMacros.cmake:80 (message):
  Macro Generators/share/egconfig/pythia8_userhooks_charm.C should be tested
Call Stack (most recent call first):
  CMakeLists.txt:102 (o2_report_non_tested_macros)
```

**Comment by Barthelemy** [comment]
@sawenzel @ktf any idea why we have this failure ?

**Comment by Barthelemy** [comment]
it is the same failure in all the PRs. Merging this one.

**Comment by tomas-herman** [comment]
Few hours ago all the PRs had the o2-dataflow build test green but now they all give this error. My PR is also affected, that's why I am interested.

**Comment by Barthelemy** [comment]
It must be something external, maybe in O2.

**Comment by ktf** [comment]
This https://github.com/AliceO2Group/AliceO2/pull/3037 seems to be the culprit.

**Comment by Barthelemy** [comment]
yes, but I really don't know how to fix it

**Comment by ktf** [comment]
Me neither. @aphecetche, maybe?

**Comment by aphecetche** [comment]
Indeed. https://github.com/AliceO2Group/AliceO2/pull/3134 should fix it (did not test it locally though, as I don't have a o2-dataflow build at hand, and doing one will take a bit...)

**Comment by Barthelemy** [comment]
@aphecetche Thank you very much, what a quick response!

**Pull request merged**
