### PR TITLE
[QC-539] Add missing level to infologger calls

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@TimoWilken @ktf any idea why the checks are red again ?

**Comment by Barthelemy** [comment]
@TimoWilken @ktf Could you check why the builds are borken ? it has been weeks

**Comment by ktf** [comment]
@TimoWilken is it actually building? I do not see any progress since this morning.

**Comment by TimoWilken** [comment]
@ktf it is now, I restarted it again this afternoon. There was a problem when I restarted this morning, which I only noticed later.

**Comment by Barthelemy** [comment]
I force the merge as it is only o2-dataflow failing with no logs and all the rest is ok.

**Pull request merged**
