### PR TITLE
Adapt to support new services API

### PR DESCRIPTION
**Pull request by ktf**
A new service declaration API will be introduced shortly. This
makes sure QC is compatible with both old and new API.

### CODE REVIEW

**Comment by ktf** [comment]
This is required to have AliceO2Group/AliceO2#3889 merged. Can we have a new tag with it?

**Comment by Barthelemy** [comment]
I will tag v0.26.3 with this commit on top of v0.26.2.

**Comment by ktf** [comment]
Thanks.

**Comment by Barthelemy** [comment]
`build/QualityControl/o2` seems stuck

**Pull request merged**
