### PR TITLE
All libraries shall go to lib64

### PR DESCRIPTION
**Pull request by Barthelemy**
Some were in lib and some were in lib64 and some were... nowhere !

### CODE REVIEW

**Comment by Barthelemy** [comment]
@awegrzyn for your information. Something to check in Monitoring as well.

**Comment by awegrzyn** [comment]
Why to `lib64` and to `lib`?

**Comment by Barthelemy** [comment]
because ${CMAKE_INSTALL_LIBDIR} defaults to lib64 (for me)

**Comment by Barthelemy** [comment]
actually, I do not hard-code it anywhere any more, I just use this variable

**Comment by awegrzyn** [comment]
So on Mac it's `lib` on CC7 `lib64` but eg. on SLC6 in my case it's not set at all... I think it's another point to investigate and decide what we shall use

**Pull request merged**
