### PR TITLE
PadCalibration Check merged for 1D and 2D + updated statistics info

### PR DESCRIPTION
**Pull request by lauraser**
This commit combines 1D and 2D checks for the PadCalibration.
It consists currently of two main parts, one check noise-related histograms and the second the rest.
For Noise histograms, a new statistics box is created which excludes the 0 entries, and quality is estimated.
For the rest, the check only estimates the quality.

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
I let @wiechula approve and it will merge afterwards.

**Review by wiechula — APPROVED** [review]
@lauraser for now this is fine, but I guess one should generalize the class a bit to be better configurable via the json and that one can use it for all PadCalibration objects.

**Comment by stheckel** [comment]
Hi @Barthelemy,
thanks for the auto-merge approval, but I fear, this was disabled by another update by Laura. As Jens has approved the last version, can you merge this PR?
Thanks!

**Comment by lauraser** [comment]
Dear all,
there is an error in o2-dataflow-cs8. From my understanding, this i not related to my code. If it is so, could you force merge? If it is related, could you help me understand why?

**Comment by stheckel** [comment]
Hi,
the error is gone again, so indeed is unrelated to the commit. At least in this moment in time there is no error at all.

**Pull request merged**
