### PR TITLE
modified json to trigger on new object

### PR DESCRIPTION
**Pull request by iravasen**

### CODE REVIEW

**Comment by JianLIUhep** [comment]
Hi @Barthelemy, is it really a clang-format error there as we only modified the json? Thanks.

**Comment by Barthelemy** [comment]
@JianLIUhep I have to check, it is a new check that replaces travis.

**Comment by Barthelemy** [comment]
https://github.com/AliceO2Group/QualityControl/pull/575 should fix it.

**Comment by iravasen** [comment]
Should I close and reopen the PR after #575 is merged or it goes automatically?

**Comment by Barthelemy** [comment]
no, I am just waiting for 02-dataflow to finish and if it is ok I will force-merge.

**Comment by Barthelemy** [comment]
errors are unrelated

**Pull request merged**
