### PR TITLE
[QC-429] NewObject trigger recognizes new objects whose validity ends before current timestamp

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by knopers8** [comment]
@tklemenz this should solve your case as well.

**Comment by tklemenz** [comment]
I cannot fully test because no new IDCs are being uploaded since yesterday morning and I cannot upload data to the test-ccdb manually for some reason. But when I run the workflow the warning about the object that the trigger is looking for doesn't show up anymore. So apparently it can find an object in the ccdb even though it is not valid at the given time. 
It seems to me that the problem is fixed. But I'll let you know once we know for sure. Thanks a lot!
Will this be in the next release?

**Comment by knopers8** [comment]
>  Will this be in the next release?

Hopefully yes.

**Review by Barthelemy — APPROVED** [review]
all good and clear !

**Pull request merged**
