### PR TITLE
FIT: all calibration tasks are turned off for global refactoring in FITCalibration libs

### PR DESCRIPTION
**Pull request by afurs**

### CODE REVIEW

**Comment by afurs** [comment]
Unrelated issue

**Review by knopers8 — APPROVED** [review]

**Comment by afurs** [comment]
@knopers8 @Barthelemy shall I restart this PR by adding new commit?

**Comment by knopers8** [comment]
o2-dataflow is spurrious and FST is already being redone, so no need to push new commits. It would be good to check if FST survives if you are disabling a few tasks. That is unless you are sure FST does not run them, then I can force-merge.

**Comment by afurs** [comment]
> o2-dataflow is spurrious and FST is already being redone, so no need to push new commits. It would be good to check if FST survives if you are disabling a few tasks. That is unless you are sure FST does not run them, then I can force-merge.

Yes, calibration tasks which are excluded for a while in this PR, are not included int FST( ft0.json config)

**Comment by knopers8** [comment]
the errors are unrelated, force-merging

**Pull request merged**
