### PR TITLE
TPC: fixed Cluster and RawDigit tasks

### PR DESCRIPTION
**Pull request by tklemenz**
- normalization to number of clusters did not work properly

### CODE REVIEW

**Comment by tklemenz** [comment]
Needs https://github.com/AliceO2Group/AliceO2/pull/7168 before merging.

**Comment by tklemenz** [comment]
Why does the check for clang-format fail even though I ran it?
Is `clang-format-6.0 -style=file -i <filename>` wrong now?

**Review by wiechula — APPROVED** [review]

**Comment by Barthelemy** [comment]
@tklemenz clang-format does not report problems on my machine either. Some extra space at the end of CheckRunner ? that's real strange.

**Comment by tklemenz** [comment]
Indeed running clang-format on CheckRunner.cxx changed the file. Apparently it did not conform.
Shall I include the file in this PR or do you want to do a separate one?

**Comment by Barthelemy** [comment]
@tklemenz Please include it in this PR even if it is not consistent with the title. I prefer to know that the change is in
The other errors seems legit ? a change is needed in O2 ?

**Comment by tklemenz** [comment]
Yes as mentioned in an earlier comment one PR in O2 is needed. But no circular dependencies this time. :)

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
