### PR TITLE
TPC: add SACs QC task

### PR DESCRIPTION
**Pull request by tklemenz**
This adds a QC task for the TPC SACs.

### CODE REVIEW

**Comment by tklemenz** [comment]
This PR needs https://github.com/AliceO2Group/AliceO2/pull/10340 from O2.

**Review by wiechula — COMMENTED** [review]
Should be checked again after the O2 part is merged

**Comment by tklemenz** [comment]
Would be good to merge https://github.com/AliceO2Group/QualityControl/pull/1640 first, then I add the option to pick the latest data from the ccdb (regardless of validity) also in this task. I only need to push. Everything is there already but functionality from the linked PR is needed.

**Comment by tklemenz** [comment]
Removing WIP to see if checks pass.

**Comment by tklemenz** [comment]
@wiechula, you can have a look when you have time.

**Comment by tklemenz** [comment]
FYI: The errors are unrelated.

**Review by wiechula — APPROVED** [review]

**Pull request merged**
