### PR TITLE
(QC-352) Functional test clean up

### PR DESCRIPTION
**Pull request by Barthelemy**
Make sure we clean up the leftovers of the functional test if any

### CODE REVIEW

**Comment by Barthelemy** [comment]
no idea why travis fails

**Comment by knopers8** [comment]
Maybe yaml files are ignored and travis fails when it is not given any files to check.

**Comment by knopers8** [comment]
There are also check results which should probably be removed as well.

**Comment by Barthelemy** [comment]
thanks, I think that you are right for travis.

**Pull request merged**
