### PR TITLE
[EMCAL-657] Trending of Occupancy per Super Module

### PR DESCRIPTION
**Pull request by cterrevo**

### CODE REVIEW

**Comment by cterrevo** [comment]
Commit tested and ready to be merged

**Comment by mfasDa** [comment]
The Werror is not so ideal: The cell index object is a well-defined structure represented as a tuple of supermodule, module and eta/phi position in the module. This fully identified the cell, and it is unnecessary to provide helper functions to access either of those information. As we anyhow have to decode the full cell index information we return this. For the purpose in the task we only need to access the supermodule ID but not the other ones, therefore the other variables are unused. The Werror prevents us from using c++17 structured binding. @Barthelemy Any way to circumvent the Werror and still use structured binding?

**Comment by knopers8** [comment]
One way to suppress the warning is to add those lines:
```
(void)mod;
(void)iphi;
(void)ieta;
```

**Comment by cterrevo** [comment]
We commited a possible solution to fix the issue.

**Pull request merged**
