### PR TITLE
Unify logging (QC-224)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@knopers8 If you look at the testQcInfoLogger you will see a number of examples demonstrating the use of the infologger. I have added a few macros. I could not find a way to avoid `endm`.

@sy-c Is there a way to omit `endm` ? Also, I see the messages arriving in a different order in the console although their timestamps are correct : 
Capture d’écran 2019-08-14 à 13 24 42

**Comment by sy-c** [comment]
Hello,

We're converting a stream into messages, so we need a separator, hence endm can not be avoided. You can use the function interface if the stream interface is not adequate for your purpose.

Concerning the order of messages: it is likely that your console is the cause of wrong display order. info messages go to stdout, and warning/errors to stderr. If you redirect stdout/stderr to different files you will likely see them in the good order.

**Comment by Barthelemy** [comment]
I am trying to use `setFMQLogsToInfoLogger` in `QcInfoLogger.h`. When I include `InfoLoggerFMQ.hxx`, I get duplicate symbols errors : 
```
duplicate symbol __Z22setFMQLogsToInfoLoggerPN7AliceO210InfoLogger10InfoLoggerE in:
    CMakeFiles/QualityControl.dir/src/ObjectsManager.cxx.o
    CMakeFiles/QualityControl.dir/src/Checker.cxx.o
```
If I use it in my test class, it is fine. Any idea ?

**Comment by Barthelemy** [comment]
I worked around it by adding an implementation file. Yet there seems to be something wrong.

**Comment by Barthelemy** [comment]
Thank you for checking the build duration. Indeed, it improves the situation. 

Concerning the LOG(DEBUG) messages, I will have a look. I don't think that it is something from this PR. Maybe something in the FMQ hook in infologger.

**Comment by Barthelemy** [comment]
`--severity-infologger info` where does this come from ? I can't find this option.

**Comment by knopers8** [comment]
You can see it if you do `o2-qc-run-basic -b --help`:
```
  --infologger-severity arg             minimun FairLogger severity which goes 
                                        to info logger
```
It is actually expected by DPL and this is what does with it:
```
      auto infoLoggerSeverity = r.fConfig.GetStringValue("infologger-severity");
      if (infoLoggerSeverity != "") {
        fair::Logger::AddCustomSink("infologger", infoLoggerSeverity, createInfoLoggerSinkHelper(infoLoggerService, infoLoggerContext));
      }
```

**Comment by Barthelemy** [comment]
@sy-c I have made a few more tests, in particular I run 
```
o2-qc-run-basic --infologger-severity info 
```
In the code I do 
```
  ILOG(Info) << "initialize SkeletonTask" << ENDM; // QcInfoLogger is used. 
  ILOG(Debug) << "ilog debug" << ENDM; 
  LOG(INFO) << "Fairmq log info";
  LOG(DEBUG) << "Fairmq log debug";
```
and I get
```
[3260:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:38:45.829649     initialize SkeletonTask
[3260:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:38:45.829657     ilog debug
[3260:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:38:45.829715     DPL: Fairmq log info
[3260:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:38:45.829727     FMQ: Fairmq log info
[3260:QC-TASK-RUNNER-QcTask]: [15:38:45][INFO] Fairmq log info
[3260:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:38:45.829750     FMQ: Fairmq log debug
```
1. The message "Fairmq log info" is repeated 3 times. It seems to be broadcasted once per DPL, once per InfoLogger and once per FMQ.
1. using infologger with debug level ("ilog debug") -> no prefix although it is not info level
2. Debug messages are there although we pass the option `--infologger-severity info`

I will WIP again this because it is not yet ready.

**Comment by Barthelemy** [comment]
If I don't use `setFMQLogsToInfoLogger(this);` I get this : 
```
[27421:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:58:36.999620     initialize SkeletonTask
[27421:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:58:36.999625     ilog debug
[27421:QC-TASK-RUNNER-QcTask]: 2019-08-30 15:58:36.999662     DPL: Fairmq log info
[27421:QC-TASK-RUNNER-QcTask]: [15:58:36][INFO] Fairmq log info
```
1. FMQ seems to be redirected to DPL anyways and it respects the level set in fmq logger. 
2. The info message in fmq is duplicated. 

Therefore, it seems a better option not to redirect ourselves fmq. 

2 problems remain : 
1. We still have to understand why we get the fmq message twice (DPL and InfoLogger) in the console
2. The debug message of infologger is passed through although we set the level at info

**Comment by Barthelemy** [comment]
first the checkers

**Pull request merged**
