### PR TITLE
CPV: make sure configure() was called in PedestalCheck

### PR DESCRIPTION
**Pull request by sevdokim**
Hello! I noticed that configure() was not called in pedestal run due to some reason. So decided to make it sure that it was called at least once before check() anything.

### CODE REVIEW

**Comment by knopers8** [comment]
@Barthelemy this does not seem correct that we do not execute `CheckInterface::configure`

**Comment by sevdokim** [comment]
hi @knopers8 
it seems to be strange for me. Locally everything is executed normally but in the production any output regarding configure() is missing at least for cpv pedestal check.

**Comment by Barthelemy** [comment]
Could you please create a ticket in JIRA explaining the issue ? we will have a look.

**Comment by sevdokim** [comment]
hi @Barthelemy 
https://alice.its.cern.ch/jira/projects/QC/issues/QC-804

**Review by Barthelemy — APPROVED** [review]
I approve because you need it but I will also investigate what is happening.

**Pull request merged**
