### PR TITLE
Update to TOF QC

### PR DESCRIPTION
**Pull request by njacazio**
- Add json configuration for the whole TOF QC chain
- Extend counter functionalities
  - Working in labelless mode
  - Skipping empty bins when filling histograms
- Merge Raw Data tasks
- Prefer counters over histograms in RawData task
- Fix compilation warning https://alice.its.cern.ch/jira/browse/QC-487

### CODE REVIEW

**Comment by njacazio** [comment]
@Barthelemy @knopers8 we are ready for review. Also, can it be that the CI is stuck?

**Comment by Barthelemy** [comment]
1. CI is broken
2. I will review.

**Review by Barthelemy — APPROVED** [review]
All good. I don't review the logic of the detectors' code but the guidelines are followed and it is will documented and very readable. Congrats and thank you.

**Comment by Barthelemy** [comment]
FYI the CI failures are followed here: https://alice.its.cern.ch/jira/browse/O2-1858

**Comment by ktf** [comment]
Can we merge this? It's one of the things which is breaking the CI.

**Comment by Barthelemy** [comment]
given the amount of changes, I would not merge it before it passes the tests. Another PR should fix a couple of tests. Let's see

**Comment by Barthelemy** [comment]
@TimoWilken I have the feeling that the mac checkers are not building
@ktf merging this as it passed the cc7 tests and we want it in

**Pull request merged**
