### PR TITLE
Create a QCDB path manager class (QC-343)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
still to be done: make sure that the class is used everyweher.

**Comment by knopers8** [comment]
Please confirm if it does not break post processing if you plan to merge it before i come back. Post processing config files use MOs and QOs paths directly, so there is a risk that something breaks.

**Comment by Barthelemy** [comment]
I did not plan to merge it before August.

**Comment by Barthelemy** [comment]
Did you approve because you tested the post-processing ?

**Comment by knopers8** [comment]
yes

**Pull request merged**
