### PR TITLE
[QC-648] Move to pub-sub for the channels between machines

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by ktf** [comment]
Can we hack this in at configuration level? Just to verify that it's indeed the issue we are observing.

**Comment by knopers8** [comment]
We can, but that will take more time to implement.

**Comment by knopers8** [comment]
@ktf If you are relying on the DDS topology files, then I suppose you could modify those channel config arguments by hand, that would be the quickest solution for you, I suppose.

**Comment by ktf** [comment]
We are now trying that with @shahor02.

**Comment by Barthelemy** [comment]
@knopers8  thank you for this very fast move. 

@ironMann Please note the comment of Piotr above

**Review by Barthelemy — APPROVED** [review]

**Comment by ironMann** [comment]
Hi. A bunch of previously working FLP-QC workflows aren't doing well since the upgrade today. How soon can this be put in place?

**Comment by Barthelemy** [comment]
Is it related ? what are the symptoms ? I would propose to move the discussion to JIRA or by email.

**Pull request merged**
