### PR TITLE
Adapt to new ConfigParamRegistry API

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
The API is going to change to allow additional feature. This should allow new and old API to work.

**Comment by knopers8** [comment]
And there is a legit compilation problem.

**Comment by ktf** [comment]
Ok, updated.

**Comment by ktf** [comment]
Merging this as everything is green and only a test was changed.

**Comment by ktf** [comment]
Can we have a new tag with this in, when you have a moment?

**Comment by Barthelemy** [comment]
ok, I will do it today.

**Pull request merged**
