### PR TITLE
Propaedeutic for AliceO2#10002 to be merged

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]

**Comment by ktf** [comment]
@chiarazampolli with this I think AliceO2Group/AliceO2#10002 should merge fine.
@Barthelemy can we have a release ASAP with this in? With the current code it's just for less boilerplate, but when #10002 is merged, it will pick up the correct callback.

**Comment by ktf** [comment]
@shahor02 FYI.

**Comment by Barthelemy** [comment]
merging as the important checks have passed

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/5011 done

**Pull request merged**
