### PR TITLE
Name Service Discovery health thread

### PR DESCRIPTION
**Pull request by awegrzyn**
I'm not sure this is 100% correct but I'd be in favour that all threads in QC/DPL are named....
FYI @ktf

### CODE REVIEW

**Comment by Barthelemy** [comment]
format issue

**Comment by Barthelemy** [comment]
Going through old PRs. Why is it still WIP ?

**Comment by awegrzyn** [comment]
I was expecting @ktf feedback on that. In general `gdb` debugging a lot easier if threads are named.

**Comment by ktf** [comment]
Yes, it should be fine. For the record, the OpenBSD man page explicitly says that the string is copied, and some of the linux versions mention the fact the string is written to /proc/self/task/[tid]/comm, so the lifetime of the string should be guaranteed by the fact that there is a copy happening at some point.

**Pull request merged**
