### PR TITLE
QC offline tracks + clusters task

### PR DESCRIPTION
**Pull request by KotliarovAr**
Task includes two executable files which open and read ROOT files with the TTree objects. Extracted data are distributed to the workflow.

### CODE REVIEW

**Comment by iravasen** [comment]
I can revise the PR for what concerns ITS functionalities.

**Comment by iravasen** [comment]
Hi @KotliarovAr, thank you! Very good piece of work. I think this is fine. One question for @Barthelemy or @knopers8: this PR contains new files, any naming convention of the files or other standards that we should follow? Thanks

**Comment by Barthelemy** [comment]
Hi, 
We follow these conventions: https://rawgit.com/AliceO2Group/CodingGuidelines/master/naming_formatting.html
We also use the prefix `run` as you noted and used.

The name of your files seem good.

**Comment by iravasen** [comment]
Thank you, then since the code structure + variable names are taken from ITSClusterTask.cxx and ITSTrackTask.cxx (already in QC since long time), I think you can merge this PR unless you have further comments/suggestions. Thanks!

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
