### PR TITLE
[OCONF-301] conventions

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@TimoWilken It seems that many builds randomly fail in QC. Could you have a look ?

**Review by knopers8 — CHANGES_REQUESTED** [review]
There are several unchanged `QualityControl` library names in Framework/CMakeLists.txt, which makes the build fail on my machine. The mac build log actually contains the message:
```
CMake Error at Framework/CMakeLists.txt:86 (target_link_libraries):
  Cannot specify link libraries for target "QualityControl" which is not
  built by this project.
  ```

**Comment by Barthelemy** [comment]
I had messed up the commits I pushed.

**Comment by Barthelemy** [comment]
@ktf any idea why we still get this error with FairLogger ?

**Comment by ktf** [comment]
No, not really. Maybe that test does not use the head of alidist? However, clearly a bunch of stuff in O2 should use `Framework/Logger.h` rather than "FairLogger.h" now that we know.

**Comment by Barthelemy** [comment]
Failure is unrelated, merging.

**Pull request merged**
