### PR TITLE
DO NOTE MERGE Try to rollback for tests

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@MichaelLettrich Any idea why the macos tests are orange ?

**Comment by MichaelLettrich** [comment]
machine got restarted apparently. I will restart the builders.

**Comment by Barthelemy** [comment]
it seems that reverting 5 commits fixes the problem ?

**Comment by Barthelemy** [comment]
still it fails in AliceO2 from time to time and in alidist, both use v0.26 so anyways I don't believe it is one specific commit.

**Comment by Barthelemy** [comment]
apparently rebooting the Mac machine solved our tests problems.

**Pull request closed without merging**
