### PR TITLE
TOF: replace TH1I histo to TH1F

### PR DESCRIPTION
**Pull request by ercolessi**
@noferini @njacazio

### CODE REVIEW

**Review by njacazio — APPROVED** [review]
Thx!

**Review by njacazio — COMMENTED** [review]
I moved to TH1D

**Comment by njacazio** [comment]
@Barthelemy somehow macOS-arm is restarting everytime and does not go to green, is this expected?

**Comment by Barthelemy** [comment]
@njacazio there is a bug. Giulio is aware.

**Pull request merged**
