### PR TITLE
[QC-388] Use timestamps in TrendingTask

### PR DESCRIPTION
**Pull request by knopers8**
After https://github.com/AliceO2Group/QualityControl/pull/458

This is an example how to retrieve data with use of timestamps. This will allow for running post-processing on older data by using triggers with associated timestamps.
@iravasen you have your own post processing tasks, so you might be interested about this.

### CODE REVIEW

**Comment by knopers8** [comment]
Hmm, the results should be also stored with the same timestamp. I have to fix that.

**Comment by knopers8** [comment]
@Barthelemy What would be the correct timestamp for post-processing results? Just like in normal MOs and QOs - from the current timestamp to 10 years in the future? Or perhaps from the first timestamp in trend, until the most recent?

Anyway, `DatabaseInterface::storeMO` has to be extended to take timestamps first.

**Comment by Barthelemy** [comment]
could you just fix the conflicts before I review ?

**Comment by knopers8** [comment]
oh, sure

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
