### PR TITLE
Use lightweight its::GeometryTGeo instead of full geometry

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by Barthelemy** [comment]
This is ok for me, there is a test failing though (full system test)

**Comment by iravasen** [comment]
Hi @Barthelemy, most probably the test `O2fst` is failing because of the modifications on the jsons. One should do the same in this json: https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/qc-sync/its.json 

Hi @shahor02, thanks a lot for the PR! Should we test it locally or you did it already?

**Comment by iravasen** [comment]
I can take care of O2DPG after lunch

**Comment by shahor02** [comment]
I am testing it locally...

**Comment by shahor02** [comment]
The problem was on the O2 side, need to wait for https://github.com/AliceO2Group/AliceO2/pull/12809 merged.

**Comment by shahor02** [comment]
@Barthelemy,  the CI is green now.

**Comment by Barthelemy** [comment]
@shahor02 Thank you !

**Pull request merged**
