### PR TITLE
Fix sporadic

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
We might have some test checking if Lifetime is Timeframe, we will see.

**Comment by ktf** [comment]
Indeed, I fixed those as well.

**Review by davidrohr — APPROVED** [review]
This passes the full system test on the EPN and at least fixes part of the problem with the rate-throttling. I think we can go ahead and merge it, and then start looking for the next issue that breaks the throttling.

**Comment by ktf** [comment]
Merging this  to get it in the nightly.

**Pull request merged**
