### PR TITLE
[EMCAL-524] Plots for different trigger classes

### PR DESCRIPTION
**Pull request by mfasDa**
- Create and fill QA plots for Calib and Physics Triggers in Raw task
- ADC range of raw amplitude projection increased in order to cover the
  range of LED events

### CODE REVIEW

**Comment by mfasDa** [comment]
@Barthelemy This is the commit in the raw task which does not depend on changes in O2. It should be handled with high priority

**Comment by Barthelemy** [comment]
@TimoWilken would it be possible to know where in the queue this PR is with regards to the macOS build ?

**Comment by TimoWilken** [comment]
@Barthelemy it's building now. There was still a problem with some of the large git repos on the CI server, I've disabled `git gc` for now, so it doesn't keep repacking them.

**Comment by mfasDa** [comment]
Build error unrelated

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
