### PR TITLE
Bug fixes for ITS Fhr task

### PR DESCRIPTION
**Pull request by JianLIUhep**

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]

**Comment by ktf** [comment]
@TimoWilken did you change the settings for those builders?

**Comment by ktf** [comment]
The macos build issues seem genuine ones.

**Comment by Barthelemy** [comment]
and that is the problem with force merging. I am going to try an fix them if I can reproduce them. 
The `o2` build is the one giving memory error.

**Comment by TimoWilken** [comment]
@ktf I gave the mesosdaq builders slightly less RAM when we had resource issues. I can restart this particular builder with more RAM assigned.

**Comment by ihrivnac** [comment]
@TimoWilken ,
What was the RAM assigned before your change and after it?

**Comment by TimoWilken** [comment]
@ihrivnac It was 20 GiB before, 16 GiB after. I've changed it back to 20 GiB. This is with 8 compiler processes running in parallel (à la `make -j 8`).

**Comment by Barthelemy** [comment]
@TimoWilken @ktf Error in build/QualityControl/o2 -> no logs

**Comment by TimoWilken** [comment]
@Barthelemy @ktf The error is:
```
ERROR: Error on 'git ls-remote --heads https://gitlab.gnome.org/GNOME/libxml2.git': fatal: unable to access 'https://gitlab.gnome.org/GNOME/libxml2.git/': The requested URL returned error: 502
```
The GNOME GitLab server is currently down until 12:00 CEST.

**Comment by ktf** [comment]
I mirrored libxml2 to alisw/libxml2 and changed the recipe.

**Comment by Barthelemy** [comment]
@TimoWilken @MichaelLettrich @ktf Mac builds still dead.

**Comment by Barthelemy** [comment]
Merging, errors unrelated.

**Pull request merged**
