### PR TITLE
Mid

### PR DESCRIPTION
**Pull request by gtaillepied**
MID folder moved under MUON
added rawDataChecker and UserLogicChecker workflows

### CODE REVIEW

**Comment by Barthelemy** [comment]
I tried to fix the conflict but I think that you need to rebase.

**Comment by aphecetche** [comment]
@gtaillepied would also probably be better to split that PR in 2 : one trivial with just the directory change (MID->MUON/MID) and another with the actual code additions.

**Comment by gtaillepied** [comment]
I removed the code additions and cleaned up the history a bit. Now this is only moving the MID folder in MUON.

**Review by Barthelemy — APPROVED** [review]

**Comment by dstocco** [comment]
@gtaillepied the Checker complains about conflicting files. Probably you need to update the master and rebase your branch to it. You will have to resolve the conflicts manually though...

**Pull request merged**
