### PR TITLE
Adjust to new TRD raw stats

### PR DESCRIPTION
**Pull request by martenole**
Will require https://github.com/AliceO2Group/AliceO2/pull/11754 to be merged first

### CODE REVIEW

**Comment by martenole** [comment]
Change of plans. Hopefully this can be merged first before the changes in O2

**Comment by martenole** [comment]
Hi @Barthelemy or @knopers8 could you please check and merge, if OK for you? Not sure why the macOS-arm check is not starting since Friday. But I need to merge some changes in O2 after and then again in QC and would like to have this before the next sw update.
The goal is for the TRD raw task to subscribe only to some statistics instead of all TRD data to allow for disabling the sampling. But for that the statistics class needs to change and this requires these subsequent updates.
Thanks!

**Comment by knopers8** [comment]
@TimoWilken, @ktf  apparently the macOS check is stuck since Friday. Could you please have a look?

**Comment by martenole** [comment]
The FST error by the way is unrelated. The check was green before

**Comment by knopers8** [comment]
> I think there is an issue with the mac builder in the DAQ lab which keeps rebooting. Can you check if it's running fine?

I don't have access to these, I'm trying to find anyone who has and isn't on holidays :/

**Comment by ktf** [comment]
Indeed the fullSystem test is now green. Merging this.

**Comment by knopers8** [comment]
I will bother you personally if this PR was failing on mac ;)

**Comment by martenole** [comment]
Personally I prefer to do it this way instead of not accepting any changes to QC until someone fixes the builders, since that seems to take some time. There will be a follow up PR and a PR in O2 that I would like to have merged before the tag for the next release is done.

**Comment by knopers8** [comment]
I agree and I just did the same with other PRs.

**Comment by ktf** [comment]
You know where to find me. ;-)

**Pull request merged**
