### PR TITLE
[MFT-5] Updating the Cluster QC task to work with the new itsmft Comp Clusters 

### PR DESCRIPTION
**Pull request by tomas-herman**
This PR already contains the changes in https://github.com/AliceO2Group/QualityControl/pull/588 which is stuck on unknown error at this time. So it also shows the changes from that PR as new.

### CODE REVIEW

**Comment by tomas-herman** [comment]
@Barthelemy the o2 test is currently in an error state but for the past 4 days it was successful so I would say it is a spurious error.

**Review by Barthelemy — APPROVED** [review]
Looks ok, I don't review the logic of modules code, only the general adherence to the coding guidelines and obvious mistakes.

**Comment by Barthelemy** [comment]
@tomas-herman Agreed, force merging

**Comment by tomas-herman** [comment]
Understood, thank you.

**Pull request merged**
