### PR TITLE
[ITS] add payload size plot to FEE task + minor improvements

### PR DESCRIPTION
**Pull request by pfecchio**

### CODE REVIEW

**Comment by iravasen** [comment]
@pfecchio please set nBins in the TH2 (y axis) in the json so that we can easily change it without going with another PR. Thank you!

**Comment by iravasen** [comment]
Thank you @pfecchio 
@Barthelemy for us this PR can be merged.

**Comment by iravasen** [comment]
My comment arrived too early. Anyway I confirm it can be merged for us. Thank you

**Comment by Barthelemy** [comment]
@TimoWilken @ktf The status of the checks have been "waiting to be reported" since yesterday. Could you have a look ?

**Comment by knopers8** [comment]
@pfecchio Is a first time contributor, but I clicked the github button to allow the checks to run. Perhaps our CI does not respond to this?

**Comment by TimoWilken** [comment]
Hi @Barthelemy, @knopers8, you're right, our CI doesn't respond to this. The checks will run if you approve the PR using the GitHub review functionality.

**Review by knopers8 — APPROVED** [review]

**Review by Barthelemy — APPROVED** [review]

**Comment by iravasen** [comment]
@Barthelemy @knopers8 can this be merged? Unfortunately from the logs I cannot see if the issue with o2-cs8 is related to "arrow" as usual.

**Pull request merged**
