### PR TITLE
TRD fix qc crashes.

### PR DESCRIPTION
**Pull request by bazinski**
- revert the connection to ccdb to be via ccdbmgr
- make the noisymcm a raw ptr.
- down the line the timestamp should be customisable from the json file, commented code left in for that.

This now works on my desktop and the epn, so hopefully good online.

### CODE REVIEW

**Review by martenole — APPROVED** [review]
Looks good to me

**Comment by Barthelemy** [comment]
the mac builder is broken, if you remove the automatic merge I will force merge.

**Review by davidrohr — APPROVED** [review]
Tried with Full System Test with QC and it solves the problem of the crash

@Barthelemy @knopers8 : Could we get this into the next QC tag?

**Comment by bazinski** [comment]
@Barthelemy I assume the request to remove the automatic merge is not to me? I understand its in the settings of the repo.

**Comment by Barthelemy** [comment]
yes it will be in the next release

**Pull request merged**
