### PR TITLE
[WIP] [QC-558] Fix the facility in IL

### PR DESCRIPTION
**Pull request by Barthelemy**
Make sure that we set the facility after all the constructors have been called.

### CODE REVIEW

**Comment by Barthelemy** [comment]
@TimoWilken The clang format test is failing on the prerequisite. Could you have a look ?

**Comment by Barthelemy** [comment]
@ktf

**Comment by Barthelemy** [comment]
@ktf @TimoWilken also `o2` build failed without logs

**Comment by TimoWilken** [comment]
@Barthelemy looking into O2; the clang-format failure has already been reported to GitHub.

**Comment by Barthelemy** [comment]
@TimoWilken I don't undersatnd why `o2` test is red.

**Comment by TimoWilken** [comment]
I've cleaned out the previous build and restarted the o2 check. Hopefully that should fix the problem.

**Comment by knopers8** [comment]
Oh, the old fairlogger problems from O2:
```
/mnt/mesos/sandbox/sandbox/qualitycontrol/sw/SOURCES/O2/build_QualityControl_o2/0/Detectors/ZDC/base/src/ModuleConfig.cxx:13:10: fatal error: FairLogger.h: No such file or directory
 #include <FairLogger.h>
          ^~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [Detectors/ZDC/base/CMakeFiles/O2lib-ZDCBase.dir/src/ModuleConfig.cxx.o] Error 1
[  2%] Built target O2test-datacompression-Fifo
/mnt/mesos/sandbox/sandbox/qualitycontrol/sw/SOURCES/O2/build_QualityControl_o2/0/Detectors/ZDC/base/src/Geometry.cxx:12:10: fatal error: FairLogger.h: No such file or directory
 #include "FairLogger.h"
          ^~~~~~~~~~~~~~
          ```

**Review by knopers8 — APPROVED** [review]
Indeed, that makes sense.

I am actually wondering if we shouldn't even set the device name there, so we can differentiate between the tasks and checkers.

**Comment by Barthelemy** [comment]
> I am actually wondering if we shouldn't even set the device name there, so we can differentiate between the tasks and checkers.

Yes, good idea. We lack a field actually. Because "facility" is `Task`, `Check` but we need to set a "process name"

**Comment by Barthelemy** [comment]
Closing in favour of https://github.com/AliceO2Group/QualityControl/pull/646

**Pull request closed without merging**
