### PR TITLE
o2sim_geometry-aligned should be used

### PR DESCRIPTION
**Pull request by chiarazampolli**
@sawenzel , @noferini , @njacazio

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @iravasen , @shahor02 , 
I see that we have o2sim_geometry.root used for ITS:
```
ITS/itsEPN.json:          "geomPath": "/home/epn/odc/files/o2sim_geometry.root",
```
Should we change this too?
Cheers,

Chiara

**Comment by iravasen** [comment]
Hi @chiarazampolli I think so. Since some months we are using the aligned one.

**Comment by shahor02** [comment]
Hi,

Should not matter for anything but tracking, which we don't do in QC, but will not hurt to change.

Cheers
  Ruben

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by chiarazampolli** [comment]
Done, @iravasen , @shahor02 .

**Review by iravasen — APPROVED** [review]

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
