### PR TITLE
new 8 plots for ITSTrackTask ClusterSize vs Chip 1st PR

### PR DESCRIPTION
**Pull request by delico18**
(TH2D) Corrected cluster size for track clusters vs Chip by Layer ( 7 plots )

(TH2D) Corrected cluster size for track clusters vs Chip Full Detector ( 1 plot )

### CODE REVIEW

**Comment by delico18** [comment]
> Hi @delico18, thanks, can you please verify that it compiles locally? I see some errors in the tests (which are all failing) which are related to your code.

I fixed tiny issue. 
 o2::itsmft::TopologyDictionary mDict; >   o2::itsmft::TopologyDictionary* mDict;

**Comment by iravasen** [comment]
@delico18 all looks good to me! There is only thing missing which is needed for the QC merger. I will add it later myself, since it takes more time to explain than to do it :-). After that I will approve the PR.

**Review by iravasen — APPROVED** [review]

**Comment by iravasen** [comment]
@Barthelemy I cannot reproduce the error shown by the O2fst/o2. It gives: 
```
reco_NOGPU.log:[127939:qc-task-ITS-ITSTrackTask]: [09:00:28][FATAL] error while setting up workflow in o2-qc: stol
```
which typically indicates that something is missing in the json.

**Comment by iravasen** [comment]
Probably I found, the json was missing in the CMakeList for some reason. Let's see if it works.

**Comment by iravasen** [comment]
> Probably I found, the json was missing in the CMakeList for some reason. Let's see if it works.

Does not work. I don't know why.

**Comment by Barthelemy** [comment]
I'll have a look later

**Pull request merged**
