### PR TITLE
Follow the latest changes of OutputSpec in O2

### PR DESCRIPTION
**Pull request by knopers8**
This has to be merged shortly after https://github.com/AliceO2Group/AliceO2/pull/2061 . I guess it will also imply having a new release in alidist.

### CODE REVIEW

**Comment by ktf** [comment]
Is this all? Everything else works as expected?

**Comment by knopers8** [comment]
Yes, the QC works, I just confirmed it. Though, mergers in O2 get some invalid input channels, I will have a closer look, please do not merge the main PR before that.

**Comment by ktf** [comment]
https://github.com/AliceO2Group/AliceO2/pull/2079

**Comment by ktf** [comment]
Ok, it looks like AliceO2Group/AliceO2#2079 is enough for this to compile, and I assume to work. This will allow merging this PR at your earliest convenience without waiting for AliceO2Group/AliceO2#2061.

**Comment by Barthelemy** [comment]
@knopers8 I will not merge myself as it requires some coordination with @ktf . I let you manage that.

**Comment by knopers8** [comment]
It is already safe to merge, since https://github.com/AliceO2Group/AliceO2/pull/2079 was merged.

**Pull request merged**
