### PR TITLE
ITS:fix some bug for FHR task

### PR DESCRIPTION
**Pull request by zla2019**
fix occupancy bug for FHR OL. use TH1::SetMaxismum, TH1::SetMinimum instead TAxis::SetRangeUser to set TH2Poly z-axis range

### CODE REVIEW

**Comment by iravasen** [comment]
Thanks a lot @zla2019! @Barthelemy, @knopers8 please wait for my checks before merge, I need to investigate 2 or 3 things more.

**Comment by Barthelemy** [comment]
@iravasen I am "WIPing" it until you are ready.

**Comment by iravasen** [comment]
All modifications included in the latest commit. PR can be merged @Barthelemy after successful tests.

**Comment by iravasen** [comment]
@Barthelemy can you please modify the title and merge it after the test? Thank you.

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
@TimoWilken Is the cs8 build working ? it has been waiting for a long time.

**Pull request merged**
