### PR TITLE
Disable test of getObjectsName

### PR DESCRIPTION
**Pull request by Barthelemy**
and prepare for next patch release

### CODE REVIEW

**Comment by Barthelemy** [comment]
cf https://github.com/alisw/alidist/pull/2226#issuecomment-622175642

**Comment by Barthelemy** [comment]
@ktf any idea why o2 is failing ?

**Comment by ktf** [comment]
No, but it's generalised. I must have screwed up something with https://github.com/alisw/ali-bot/pull/755. :-/ I will let you know when I understand.

**Comment by Barthelemy** [comment]
no idea why I have to force merge but all tests have passed and it was approved.

**Pull request merged**
