### PR TITLE
ITSRawTask supports the updated math_utils

### PR DESCRIPTION
**Pull request by JianLIUhep**

### CODE REVIEW

**Comment by Barthelemy** [comment]
This won't work until https://github.com/AliceO2Group/AliceO2/pull/4607 is merged.

**Comment by Barthelemy** [comment]
fixing it to be compatible with https://github.com/AliceO2Group/AliceO2/pull/4663

**Comment by Barthelemy** [comment]
As alibuild decided to rebuild Clang this is going to take a few more hours than expected

**Comment by Barthelemy** [comment]
@TimoWilken It seems that the build "QualityControl/o2-dataflow" is marked as generated by you. Perhaps it should say "generated by alibuild"

**Comment by TimoWilken** [comment]
@Barthelemy, it's using a temporary auth token I generated. It'll be back to alibuild in a while!

**Comment by davidrohr** [comment]
@Barthelemy : The QC CI has passed, can you create a tag?

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
@davidrohr yes

**Comment by Barthelemy** [comment]
@davidrohr https://github.com/alisw/alidist/pull/2561

**Pull request merged**
