### PR TITLE
MFT: New histograms for the cluster task and new url for the consul.

### PR DESCRIPTION
**Pull request by tomas-herman**
Adding further histograms to the cluster task. Updating the url for the consul. Update of header file table.

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
Please check the formatting

**Comment by tomas-herman** [comment]
Hi @Barthelemy, I have checked all the files in the MFT folder and they all seem to be formatted correctly (following instructions here: https://github.com/AliceO2Group/CodingGuidelines#formatting-tool).  Looking at the clang check I cannot find hints on what file is triggering the error. Could you have a look and let me know what file is causing the issue?

**Comment by Barthelemy** [comment]
@tomas-herman I don't understand either. Nothing is wrong. 
I will touch a file to re-trigger the check.

**Comment by tomas-herman** [comment]
Seems it failed again with the same error.

**Comment by Barthelemy** [comment]
have you rebased ? 
The line numbers don't match mines.

**Comment by tomas-herman** [comment]
My master branch from which I started developing (https://github.com/tomas-herman/QualityControl) is 16 commits behind the O2 master. I checked and the commits did not involve MFT Module so I though it is ok.

**Comment by tomas-herman** [comment]
When comparing the AliceO2 master and the branch in the PR it really seems that the only changes are corresponding to the development. There were some changes in the includes at the beginning of the files so this might cause the shift in lines. Is there something specific you had in mind?

**Comment by Barthelemy** [comment]
Not really, just trying things :) I will merge because all the rest passes.

**Pull request merged**
