### PR TITLE
[MCH] [MRRTF-108] Prepare for digit move

### PR DESCRIPTION
**Pull request by aphecetche**
We will be moving Digit.h from MCHBase to DataFormatsMCH in AliceO2. 
This PR hopefully makes the QC immune to that forthcoming change.

### CODE REVIEW

**Comment by aphecetche** [comment]
@aferrero2707 this is to avoid breaking the QC compilation when we'll change the home of our MCH Digit.h (in a forthcoming PR in AliceO2)

**Review by Barthelemy — CHANGES_REQUESTED** [review]
The file Modules/Example/README.md seems to have been automatically added. Could you remove it ? 
Otherwise, all good !

**Comment by aphecetche** [comment]
@Barthelemy have no idea how this empty Modules/Example/README.md ended up there, but it should be fixed now.

**Review by Barthelemy — APPROVED** [review]

**Comment by aphecetche** [comment]
@Barthelemy all green

**Pull request merged**
