### PR TITLE
PHOSrawQC

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
Not sure that 3 failed test has something with PHOS:
	 25 - testCheckWorkflow (Timeout)
	 26 - testWorkflow (Timeout)
	 30 - functional_test (Timeout)

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
macOS erros: false positive
@ktf @TimoWilken Any idea why the other builds are failing ?

**Comment by TimoWilken** [comment]
Hm, the o2-dataflow test seems to have fixed itself. I've restarted build/QC/o2 and the MacOS test, for good measure.

**Comment by peressounko** [comment]
macOS result is stable: same tests failed
         25 - testCheckWorkflow (Timeout)
	 26 - testWorkflow (Timeout)
	 30 - functional_test (Timeout)

**Comment by peressounko** [comment]
Dear @TimoWilken , @Barthelemy could we merge this PR - we would like to install it at EPN and try with data. Thanks, Dmitri

**Comment by Barthelemy** [comment]
merged !

**Pull request merged**
