### PR TITLE
Install tests under tests

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by knopers8** [comment]
In testInfrastructureGenerator.cxx the config file path is .../**test**/testQCFactory.json, could you change it to **tests**?

**Comment by Barthelemy** [comment]
1. The CI should use `make test` which is unchanged. 
2. yes, I am going to do it now.

**Comment by Barthelemy** [comment]
2. Done but testInfrastructureGenerator fails for other reasons now. I'll let you check, probably in a different PR, what the problems are.

**Comment by knopers8** [comment]
OK, I will have a look, thanks.

**Pull request merged**
