### PR TITLE
[EMCAL-526] Plots for different trigger classes

### PR DESCRIPTION
**Pull request by mfasDa**
Create and fill QA plots for Calib and Physics Triggers in Digit task

### CODE REVIEW

**Comment by mfasDa** [comment]
@Barthelemy This is the commit in the cell task, which need changes in O2

**Comment by mfasDa** [comment]
@Barthelemy @knopers8 The new tag is out (v21.03). Could someone of you please restart the mac CI test? Thanks!

**Comment by ktf** [comment]
@TimoWilken can you have a look on what is the actual error?

**Comment by ktf** [comment]
to be clear, it's red, but I cannot find anything wrong.

**Comment by Barthelemy** [comment]
me neither, I let the macOS build finish but if it stays like that I merge

**Comment by TimoWilken** [comment]
I've restarted them, but it turns red again for an error in the CI.

@ktf: somehow aliBuild is trying to depend on a wrong version number.
```
2021-01-21@15:43:16:DEBUG:QualityControl:O2:build_QualityControl_o2: ++ source /mnt/mesos/sandbox/sandbox/qualitycontrol/sw/slc7_x86-64/boost/v1.74.0-46/etc/profile.d/init.sh
2021-01-21@15:43:16:DEBUG:QualityControl:O2:build_QualityControl_o2: /mnt/mesos/sandbox/sandbox/qualitycontrol/sw/slc7_x86-64/arrow/v1.0.0-49/etc/profile.d/init.sh: line 2: /mnt/mesos/sandbox/sandbox/qualitycontrol/sw/slc7_x86-64/boost/v1.74.0-46/etc/profile.d/init.sh: No 
such file or directory
2021-01-21@15:43:16:ERROR:QualityControl:O2:build_QualityControl_o2: Error while executing /mnt/mesos/sandbox/sandbox/qualitycontrol/sw/SPECS/slc7_x86-64/O2/build_QualityControl_o2-1/build.sh on `alientest02'.
```
It's an error I thought should've been fixed by https://github.com/alisw/alibuild/pull/638, but apparently not.

**Comment by Barthelemy** [comment]
Honestly I don't see how we can have this commit in an RPM for tomorrow with an unfinishing macOS build and the two others broken.

**Comment by mfasDa** [comment]
The two broken build tests are false positives

**Comment by Barthelemy** [comment]
ok very good, merging and generating the RPMs while the alidist PR carries on !

**Pull request merged**
