### PR TITLE
FT0 DigitQcTask: hotfix for chID per BC plot

### PR DESCRIPTION
**Pull request by afurs**
Trivial, needed at P2

### CODE REVIEW

**Comment by afurs** [comment]
Hi @Barthelemy , this is trivial hotfix, we would to have it at P2(next FLP release) ASAP. Could you please skip CICD?

**Comment by Barthelemy** [comment]
Hi @afurs , I can skip the CI but that does mean that it will end up faster at P2 in the FLP Suite. Do you need me to do a patch version with it ?

**Review by Barthelemy — APPROVED** [review]

**Comment by afurs** [comment]
> I can skip the CI but that does mean that it will end up faster at P2 in the FLP Suite

Yes, please patch it. Thanks!

**Comment by afurs** [comment]
@Barthelemy for now we have this task only on FLP, but soon it may be migrated into EPN part. At QC node we cannot deploy such task.

**Comment by Barthelemy** [comment]
@afurs ok then we need new rpms. I'll ask @vascobarroso

**Pull request merged**
