### PR TITLE
Use DPL Task API in TaskRunner

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf @dberzano any idea what is this error in the o2 build ? 
```c++: error: vfork: Cannot allocate memory```

**Comment by Barthelemy** [comment]
@knopers8 nice, it simplifies considerably the code. I will test it but I have to rebuild something else first.

**Comment by dberzano** [comment]
@Barthelemy it's an error due to the lack of resources on the running node. I am restarting the worker just to be sure.

**Comment by ktf** [comment]
I think there is actually something which is exhausting PIDs on the builder nodes. I've just done the same for the O2 builders.

**Pull request merged**
