### PR TITLE
TRD noise removal from plots

### PR DESCRIPTION
**Pull request by bazinski**
Remove the noisy MCMs from the tracklets plots and pulseheight plots.
Keep both the noisy and new plots.
The noisy plots might get removed later.
2 Tasks, pulseheight and tracklettask make connection to ccdbapi, this will of course change later.

### CODE REVIEW

**Comment by Barthelemy** [comment]
the test failures seem legit.

**Comment by bazinski** [comment]
oui, I am at home sick will get back to this once fully functional.

**Comment by bazinski** [comment]
Hi @Barthelemy 
That should be better, forgot to remove noise.cxx|h from cmake and linkdef.

**Comment by Barthelemy** [comment]
@TimoWilken The two failing tests don't have logs.

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
