### PR TITLE
TPC Trending json (Tracks and PID)

### PR DESCRIPTION
**Pull request by mlesch**

### CODE REVIEW

**Comment by stheckel** [comment]
Hi Marcel,
thanks for the trending json! One comment: In the CMakeList, can you please instead of changing the name of the json just add the new one? Otherwise the old file could not be run anymore.
Thanks and cheers,
Stefan

**Comment by mlesch** [comment]
Hi Stefan, 
Thanks for the comment, it is updated now.
Cheers,
Marcel

**Review by wiechula — APPROVED** [review]

**Comment by stheckel** [comment]
Hi @Barthelemy, hi @knopers8,
could you have a look at this PR and approve it? Its just a json file for some TPC trendings. Jens approved it, but this seems not to be enough to start the checks.
Thanks and cheers,
Stefan

**Comment by stheckel** [comment]
Hi,
this is strange, two checks fail although this is just a json configuration file. The issue is in a memory test and the same issue is also observed in another PR. So I guess, it is not related to these commits here, but I am also not entirely sure...

**Comment by Barthelemy** [comment]
The failures are not even in QC. They are in O2. I force merge.

**Pull request merged**
