### PR TITLE
[EMCAL-527] Adding RawCheck

### PR DESCRIPTION
**Pull request by cterrevo**
Implemented Checks:
- checker for ErrorType histogram

### CODE REVIEW

**Comment by cterrevo** [comment]
The RawCheck compiles and does not crash. Functional tests will be done when QC GUI will support the checker.

**Comment by mfasDa** [comment]
@Barthelemy @cterrevo There is a PR to be merged in AliceO2 (https://github.com/AliceO2Group/AliceO2/pull/3035) that will break compilation of QualityControl. The PR is ready and will be merged soon. Either this PR must be merged now or it must wait for the adaption of the fix adapting the EMCAL component to the fix mentioned above.

**Comment by mfasDa** [comment]
Depends on https://github.com/AliceO2Group/QualityControl/pull/326

**Comment by ktf** [comment]
The test happened and seems to have been successful, however reporting to Github seems to have failed. Investigating what happened and bumping the build to force testing again.

**Comment by ktf** [comment]
Ok, problem understood. It was actually a typo introduced by alisw/ali-bot#737. alisw/ali-bot#739 fixes it.

**Comment by mfasDa** [comment]
PR checker error not related to this commit.

**Comment by knopers8** [comment]
Not related indeed, but the CI doesn't report how did the QC build go, so I would have to merge blindly.

**Pull request merged**
