### PR TITLE
add TOF match histos for experts

### PR DESCRIPTION
**Pull request by noferini**
Add some histos to check the quality of the matching and alignment strip by strip using high pT tracks (default: pT > 2).

@njacazio, @ercolessi

### CODE REVIEW

**Comment by njacazio** [comment]
Ciao Francesco, is it still WIP?

**Comment by noferini** [comment]
> Ciao Francesco, is it still WIP?
Yes, I need to test it and I have some other histos I would add.
More news soon.
Cheers,
Francesco

**Comment by noferini** [comment]
Now it looks fine in my tests.
Ready for the review.
Cheers,
Francesco

**Comment by njacazio** [comment]
Perfect, does it impact the json as well?

**Comment by noferini** [comment]
> Perfect, does it impact the json as well?

No, I just added few histos but not the json.
There is an extra param to set the pT threshold for the new histogram (default -> 2 GeV/c) but we can stay with the default.

**Review by njacazio — APPROVED** [review]
Perfect, thanks!

**Review by njacazio — APPROVED** [review]

**Review by njacazio — APPROVED** [review]

**Comment by njacazio** [comment]
But it's never merging!

**Pull request merged**
