### PR TITLE
add ITS online data processing fake-hit rate task

### PR DESCRIPTION
**Pull request by JianLIUhep**
Already veirfied with the chain of "Detector -> RU -> CRU -> Readout -> STFB -> DPL + QC".
This is dedicated to the final version. The ITSRawTask aiming at ITS commissioning phase would become obsolete as soon as we have a stable online version, and could be removed then. 

The related O2 merge request can be found here: https://github.com/AliceO2Group/AliceO2/pull/3954

### CODE REVIEW

**Comment by JianLIUhep** [comment]
Dear Reviewers, I changed this PR to WIP as we first need to proceed with the modifications in O2. Anyway, you can have a look at this PR in advance if possible as the skeleton would not be changed a lot.

**Comment by JianLIUhep** [comment]
RawPixelDecoder modified w.r.t. ITS QC (https://github.com/AliceO2Group/AliceO2/pull/3999), and the QC modifications were done. 
Waiting for the modification (discussion) of the data sampling description: https://alice.its.cern.ch/jira/browse/QC-367

**Comment by JianLIUhep** [comment]
Dear Reviewers, this PR is ready for review. Thank you.

**Review by knopers8 — CHANGES_REQUESTED** [review]
Hello, I see that the following class member pointers are not deleted in the destructor:
```
  TH2I* mErrorVsFeeid;
  TH2I* mTriggerVsFeeid;

  //TH1D* mInfoCanvas;//TODO: default, not implemented yet
  TH2I* mInfoCanvasComm; //tmp object decidated to ITS commissioning
  TText* mTextForShifter;
  TText* mTextForShifter2;

  TH2I* mChipStaveEventHitCheck[7];

  ChipPixelData* mChipDataBuffer = nullptr;
```
Could you please make sure they are deleted? Your task might be deleted and created across many runs, that could create memory leaks.

**Comment by JianLIUhep** [comment]
Hi, the variables are deleted in the destructor and the unused headers are also removed.

**Review by knopers8 — APPROVED** [review]

**Comment by JianLIUhep** [comment]
It seems this PR cannot trigger the Travis CI again (the same as my previous PR)...
Are there any problems concerning my account or PR settings?

**Comment by knopers8** [comment]
You're not a first time contributor, so I wouldn't expect any other reason why Travis might not be triggered for you. @ktf Any idea?

**Comment by ktf** [comment]
I do not have control on the QualityControl Travis, AFAICT. @awegrzyn should probably have a better idea. I suppose it's a Travis quirk.

**Comment by awegrzyn** [comment]
So what I found in Travis docs is that the builds are branch triggered, therefore the owner of the fork should add travis integration to its repo and start a build. Once it's done the check in here will turn green/red, otherwise it will remain "Expected" indefinitely.

**Comment by knopers8** [comment]
But I don't have Travis enabled for my fork, and for some reason it works if I submit a PR to this repo.

**Comment by JianLIUhep** [comment]
Travis CI passed in my repo:
https://travis-ci.org/github/JianLIUhep/QualityControl/builds/727631512

**Comment by knopers8** [comment]
Wow, now we can't get any check results.

**Comment by JianLIUhep** [comment]
Hi @awegrzyn, I enabled the Travis in my repo and the PR passed the build, and also authorized ALICE Continuous Integration in my github account. But they seemed to be still not working.

**Comment by awegrzyn** [comment]
Hi,
I've noticed that your repo uses `travis-ci.org` and `AliceO2` repos already migrated to `travis-ci.com`? Could you to the same? They should be dedicated button to do so in Travis Settings.

**Comment by knopers8** [comment]
@Barthelemy Could you have a look at the travis settings for our repo? It seems that our travis is associated with your account, or at least I don't know how to find it.

**Comment by JianLIUhep** [comment]
@knopers8 @Barthelemy The Travis in my repo was travis-ci.org and just moved to travis-ci.com. But "Abuse detected" when I pushed. Asking the Travis support for help.

**Comment by awegrzyn** [comment]
I'd just force merge it, I expect it will work fine next time

**Comment by knopers8** [comment]
Yeah, I saw the build already passing, so I am fine with merging this. I've just confirmed locally that clang-format doesn't have any suggestions. macOS build failed due to testFactory which is unrelated.
@JianLIUhep Sorry that you were to experience all of those problems with CI.

**Comment by JianLIUhep** [comment]
Thanks a lot for your help. Now I can trigger the build in my repo with `travis-ci.com`. 
https://travis-ci.com/github/JianLIUhep/QualityControl/builds/184896672
Let's see if it works in my next PR.

**Pull request merged**
