### PR TITLE
[FIT] Use proper getters from fit::Triggers class

### PR DESCRIPTION
**Pull request by mslupeck**
Code cleanup - no functional changes

### CODE REVIEW

**Review by knopers8 — DISMISSED** [review]

**Comment by knopers8** [comment]
actually, the fst failure looks relevant:
```
[135502:qc-task-FV0-DigitQcTaskFV0]: *** Segmentation fault (O2)
[135502:qc-task-FV0-DigitQcTaskFV0]: Backtrace:
[135502:qc-task-FV0-DigitQcTaskFV0]:     /lib64/libc.so.6: ()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/QualityControl/1371-slc7_x86-64-local1/lib/libO2QcFV0.so: o2::quality_control_modules::fv0::DigitQcTask::monitorData(o2::framework::ProcessingContext&)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/QualityControl/1371-slc7_x86-64-local1/lib/libO2QualityControl.so: o2::quality_control::core::TaskRunner::run(o2::framework::ProcessingContext&)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: ()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: o2::framework::DataProcessingDevice::tryDispatchComputation(o2::framework::DataProcessorContext&, std::vector<o2::framework::DataRelayer::RecordAction, std::allocator<o2::framework::DataRelayer::RecordAction> >&)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: o2::framework::DataProcessingDevice::doRun(o2::framework::DataProcessorContext&)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: o2::framework::DataProcessingDevice::Run()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQ.so.1.4: fair::mq::Device::RunWrapper()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQStateMachine.so.1.4: boost::detail::function::void_function_obj_invoker1<std::function<void (fair::mq::State)>, void, fair::mq::State>::invoke(boost::detail::function::function_buffer&, fair::mq::State)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQStateMachine.so.1.4: boost::signals2::detail::signal_impl<void (fair::mq::State), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (fair::mq::State)>, boost::function<void (boost::signals2::connection const&, fair::mq::State)>, boost::signals2::mutex>::operator()(fair::mq::State)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQStateMachine.so.1.4: fair::mq::fsm::Machine_::ProcessWork()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQStateMachine.so.1.4: fair::mq::StateMachine::ProcessWork()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/FairMQ/v1.4.52-3/lib/libFairMQ.so.1.4: fair::mq::DeviceRunner::Run()
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: doChild(int, char**, o2::framework::ServiceRegistry&, o2::framework::RunningWorkflowInfo const&, o2::framework::RunningDeviceRef, o2::framework::ProcessingPolicies, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, uv_loop_s*)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: runStateMachine(std::vector<o2::framework::DataProcessorSpec, std::allocator<o2::framework::DataProcessorSpec> > const&, WorkflowInfo const&, std::vector<o2::framework::DataProcessorInfo, std::allocator<o2::framework::DataProcessorInfo> > const&, o2::framework::CommandInfo const&, o2::framework::DriverControl&, o2::framework::DriverInfo&, std::vector<o2::framework::DeviceMetricsInfo, std::allocator<o2::framework::DeviceMetricsInfo> >&, boost::program_options::variables_map&, std::vector<o2::framework::ServiceSpec, std::allocator<o2::framework::ServiceSpec> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
[135502:qc-task-FV0-DigitQcTaskFV0]:     /sw/slc7_x86-64/O2/1371-slc7_x86-64-local1/lib/libO2Framework.so: doMain(int, char**, std::vector<o2::framework::DataProcessorSpec, std::allocator<o2::framework::DataProcessorSpec> > const&, std::vector<o2::framework::ChannelConfigurationPolicy, std::allocator<o2::framework::ChannelConfigurationPolicy> > const&, std::vector<o2::framework::CompletionPolicy, std::allocator<o2::framework::CompletionPolicy> > const&, std::vector<o2::framework::DispatchPolicy, std::allocator<o2::framework::DispatchPolicy> > const&, std::vector<o2::framework::ResourcePolicy, std::allocator<o2::framework::ResourcePolicy> > const&, std::vector<o2::framework::CallbacksPolicy, std::allocator<o2::framework::CallbacksPolicy> > const&, std::vector<o2::framework::SendingPolicy, std::allocator<o2::framework::SendingPolicy> > const&, std::vector<o2::framework::ConfigParamSpec, std::allocator<o2::framework::ConfigParamSpec> > const&, o2::framework::ConfigContext&)
[135502:qc-task-FV0-DigitQcTaskFV0]:     o2-qc() [0x4186f0]
[135502:qc-task-FV0-DigitQcTaskFV0]:     o2-qc() [0x412148]
[135502:qc-task-FV0-DigitQcTaskFV0]:     /lib64/libc.so.6: __libc_start_main()
[135502:qc-task-FV0-DigitQcTaskFV0]:     o2-qc() [0x41222e]
[135502:qc-task-FV0-DigitQcTaskFV0]: Backtrace complete.
```

**Comment by mslupeck** [comment]
Hi @knopers8 
Actually, I can't reproduce this error locally. And considering the changes applied to FV0DigitQcTask (which failed in these CI tests) are very basic (changing access by data member to access by getters), I'll only restart the tests this time, hoping it was just a glitch on the CI machine.

**Comment by knopers8** [comment]
Sorry, it seems it crashed in the same place.

**Comment by mslupeck** [comment]
Yes, I saw that during the weekend, but I'm lost on what to do next. Maybe I'll try to revert my modifications on the offending file, but I have to do it here because locally all tests succeed.
Anyway, thanks for noticing it in the first place!

**Comment by knopers8** [comment]
Maybe the config file which is used in FST is just obsolete?
https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/qc-sync/fv0.json

**Comment by afurs** [comment]
I suppose this thing crashes: https://github.com/AliceO2Group/AliceO2/blob/2c723a8ed7662de7b00be235cb72fbb6bc4ce564/DataFormats/Detectors/FIT/common/include/DataFormatsFIT/Triggers.h#L73

**Comment by mslupeck** [comment]
Thanks @afurs !
I'll change it in O2, and come back to this PR later

**Comment by mslupeck** [comment]
@knopers8 This time, I think the error is not related.
The previous problem was using the possibly negative value to the array index. With this PR (https://github.com/AliceO2Group/AliceO2/pull/9587) it should not be the case anymore.

**Comment by knopers8** [comment]
Indeed, but the current error prevents a certain workflow from being ran at all, so we do not know whether the test would normally succeed or not:
```
reco_NOGPU.log:terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
reco_NOGPU.log-  what():  option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log:terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
reco_NOGPU.log-  what():  option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log:[ERROR] error while setting up workflow in o2-tpc-idc-factorize: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
reco_NOGPU.log:[ERROR] Dynamic exception type: boost::wrapexcept<boost::program_options::multiple_occurrences>
reco_NOGPU.log:[ERROR] std::exception::what: option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log-[ERROR] 
```
We do not plan to release very soon, so if it is OK with you, we could wait until it becomes green.

**Review by knopers8 — APPROVED** [review]

**Comment by knopers8** [comment]
Oh, so FST is not mandatory to merge the PR apparently. OK, too late.

**Pull request merged**
