### PR TITLE
[FIT] Use dead channel map from CCDB and add BC distr per trigger

### PR DESCRIPTION
**Pull request by sbysiak**

### CODE REVIEW

**Comment by knopers8** [comment]
Hi @sbysiak , the failures on Ci look legit:
```
                        ^
input_line_9:607:10: fatal error: 'DataFormatsFIT/BadChannelMap.h' file not found
#include "DataFormatsFIT/BadChannelMap.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         ```

**Comment by sbysiak** [comment]
> Hi @sbysiak , the failures on Ci look legit:
> 
> ```
>                         ^
> input_line_9:607:10: fatal error: 'DataFormatsFIT/BadChannelMap.h' file not found
> #include "DataFormatsFIT/BadChannelMap.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>          ```
> ```

yes, there was change in O2, I will have to adjust

**Review by knopers8 — APPROVED** [review]

**Comment by mslupeck** [comment]
@knopers8 I think this will not automerge because of an unrelated error. Do we need to restart the tests or can you merge it manually?

**Comment by knopers8** [comment]
@mslupeck Yes indeed, I hoped that the macOS issues are resolved in short time. Are you in hurry? I would prefer to have the macOS test run, since LLVM sometimes detects issues which are not seen by GCC.

@TimoWilken Could you please have a look at the macOS issue?

**Comment by mslupeck** [comment]
> @mslupeck Yes indeed, I hoped that the macOS issues are resolved in short time. Are you in hurry?
Not in a big hurry, but it would be nice to get it merged so that it could be deployed at p2 and tested still before winter break.

**Pull request merged**
