### PR TITLE
Avoid copy

### PR DESCRIPTION
**Pull request by ktf**
This triggers some of the copies / deletions which you see.

### CODE REVIEW

**Comment by ktf** [comment]
Proper fix to avoid the copy completely coming up in the Framework.

**Review by knopers8 — APPROVED** [review]
I don't understand, but I trust you.

As far as I can tell, `DeviceSpec` does not contain any `framework::Task`, how does it help?

**Comment by ktf** [comment]
It contains the AlgorithmSpec, which contains the captured task. I am changing a few things in DPL to prevent any copy of those.

**Comment by knopers8** [comment]
OK, indeed, thanks

**Comment by ktf** [comment]
Sorry guys, I need a patch also with this...

**Pull request merged**
