### PR TITLE
TRD digit QC protection against division by zero

### PR DESCRIPTION
**Pull request by martenole**
Fix for FPE observed in alibi nightly MC tests.
Ping @knopers8

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @martenole , @knopers8 , 

We will need a new tag from QC for PbPb with this fix. Can this be done? We would need it as soon as possible - as always :-) 

Cheers,
Chiara

**Comment by chiarazampolli** [comment]
Actually, at the moment we are using v1.123.0, so the bug is not there. But in general, we should understand how to handle data and MC when we use dev/master of O2/O2DPG, but an "old" tag from QC...

**Comment by martenole** [comment]
Hi @chiarazampolli the bug has been there for a very long time. Also in v1.123.0 it is present. It is just very unlikely to have zero tracklets for a whole TF that's why it appeared only once now. I doubt it will ever happen in PbPb, but still I think it would be better to have the protection in..

**Comment by martenole** [comment]
> Hello @martenole , Was it not introduced here?

Yes, you are right, sorry. Indeed I introduced the bug in https://github.com/AliceO2Group/QualityControl/pull/2037 and checked wrongly for an older version

**Pull request merged**
