### PR TITLE
ITS: NCluster plot moved to Double

### PR DESCRIPTION
**Pull request by IsakovAD**
Changed type of the nClustersPerTrack histogram from float to double. 

This change should fix problem for a-QC where we have overflow of float limits

### CODE REVIEW

**Comment by IsakovAD** [comment]
Hello @iravasen 

Could you please approve this request? This is trivial solution to a-QC problem

**Review by iravasen — APPROVED** [review]

**Review by iravasen — CHANGES_REQUESTED** [review]
@IsakovAD thanks, you need also to modify the checkers. Example, this line: https://github.com/AliceO2Group/QualityControl/blob/635ab2651c8a4f01b316aed4b5d02d31ac8dd414/Modules/ITS/src/ITSTrackCheck.cxx#L42

**Comment by iravasen** [comment]
No wait sorry you did it! I did not see it. 

Then I think you can also modify the cluster task. In particular the 1D cluster size distributions.

**Comment by IsakovAD** [comment]
Hello @iravasen 

I moved all the plots in Cluster/Track tasks to the Double. FEE task and Decoding error are already fine;

**Review by iravasen — APPROVED** [review]
Thanks a lot! Approving

**Pull request merged**
