### PR TITLE
Update tof json for full QC

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Review by knopers8 — COMMENTED** [review]
Do you really need the same tasks running both locally and remotely? See `TaskRaw` and `TaskRawRemote` for example.

**Comment by njacazio** [comment]
@knopers8 now it should be ok

**Comment by knopers8** [comment]
I tihnk you didn't `git add toffull_multinode_flp_epn.json`

**Comment by knopers8** [comment]
One build did not provide results, others are fine, merging.

**Review by knopers8 — APPROVED** [review]

**Pull request merged**
