### PR TITLE
Modified Tracklet Task

### PR DESCRIPTION
**Pull request by shsharma1**
Added two histograms: 1)Digits Per Event 2)Events with digits per Timeframe

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
please fix the formatting

**Comment by shsharma1** [comment]
> All the changes here seem to be for digits, yet this is all within the trackletstask file.

Yes changes here are for the digits. So, should we do make changes to digitstask?

**Comment by shsharma1** [comment]
> please fix the formatting

In new PR 1504 I have fixed the formatting by running "clang-format -i ...."

**Comment by knopers8** [comment]
> > please fix the formatting
> 
> In new PR 1504 I have fixed the formatting by running "clang-format -i ...."

You do not have to open a new PR when you apply some additional changes. You can just push to the same branch.

**Comment by knopers8** [comment]
Also, please close one of the PRs if you do not want both to be merged

**Pull request closed without merging**
