### PR TITLE
[WIP][O2-4122, EMCAL-1037] Move to DPL CCDB Backend

### PR DESCRIPTION
**Pull request by mfasDa**
Use DPL CCDB Backend for accessing the trigger
configuration.

### CODE REVIEW

**Comment by mfasDa** [comment]
Set to WIP because query of `ccdb-run-dependent` currently ends in fatal as all attributes in DataDescriptorQueryBuilder are parsed as string while bool is expected, leading to a type mismatch fatal.

**Comment by mfasDa** [comment]
Do not merge yet! In the current state the feature is unusable for us. Run-dependent queries are essential, the task will produce nonsense otherwise.

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/AliceO2/pull/11917

**Comment by Barthelemy** [comment]
@mfasDa What should we do with this PR?

**Comment by mfasDa** [comment]
@Barthelemy I hope at some point fix the underlying problem. But we cannot merge it yet as the task doesn't get the CCDB objects in case a data sampling policy is applied, which we have to do. The CCDB backend seems to work only for direct data sources.

**Pull request closed without merging**
