### PR TITLE
Fix missing ptree header

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
One more which will be needed. Maybe we should do a round of "include what you use"...

**Comment by Barthelemy** [comment]
Any tool I could use to help with that ?

**Comment by ktf** [comment]
"include what you use" is the name of the tool :-) [Who's on first.](https://youtu.be/kTcRRaXV-fg?t=91)

**Comment by ktf** [comment]
I mean, https://github.com/include-what-you-use/include-what-you-use

**Comment by ktf** [comment]
Can you tag this as well, when you have time?

**Pull request merged**
