### PR TITLE
A QC Task to try publishing different ROOT objects

### PR DESCRIPTION
**Pull request by knopers8**
I used it to look for potential leaks in TCanvas, but this Task could be useful for similar investigations in the future, even if it does not cover every popular ROOT class yet.

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]
Very useful. One missing type perhaps, for a future iteration, is TTree.

**Comment by Barthelemy** [comment]
@TimoWilken Is the mac builder ok ?

**Comment by TimoWilken** [comment]
The Mac builder is up, it's just been testing a queue of PRs -- this PR got unlucky; the last check for new PRs was a minute before this one was submitted. It should be picked up soon.

**Comment by Barthelemy** [comment]
@TimoWilken Thanks a lot.

**Pull request merged**
