### PR TITLE
[QC-509] Clear warnings

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@JianLIUhep

**Comment by JianLIUhep** [comment]
Thank you @Barthelemy. It seems the same fix should also be carried out for ITSTrackCheck.cxx and ITSFeeCheck.cxx.

**Comment by JianLIUhep** [comment]
And the **++iter** for ITSFhrCheck.cxx

**Comment by Barthelemy** [comment]
@JianLIUhep Yes, correct, I am going to do that.

**Pull request merged**
