### PR TITLE
Use new TPC cluster reader helper to avoid copy&pasted code

### PR DESCRIPTION
**Pull request by davidrohr**
no functionall change, just getting rid of some copy&pasted code, tested already and histograms are published to the qcg-test website in the same way as before.

### CODE REVIEW

**Comment by davidrohr** [comment]
@Barthelemy @TimoWilken : What is QC/o2-dataflow tested against? Is it o2 dev branch? I am wondering how it can still fail, since the problem in O2 is fixed, and I could compile O2 and QC with my patch with o2-dataflow defaults locally.

**Comment by Barthelemy** [comment]
I am not sure. Timo, could you check ? I suspect that it is against the alidist defined version of O2 which would be incorrect.

**Comment by TimoWilken** [comment]
@davidrohr @Barthelemy it's tested against what's defined in the master branch of alidist, so right now it's v21.01.

**Comment by davidrohr** [comment]
ok, so this is the reason why it is failing, since the tag lacks the latest fixes in O2/dev. Shouldn't it be checked against dev?

**Comment by Barthelemy** [comment]
I agree, I would prefer if it was tested against dev.

**Comment by TimoWilken** [comment]
See: https://github.com/alisw/ali-bot/pull/931

**Comment by davidrohr** [comment]
@Barthelemy : Something is stange here. Both dataflow CIs have been green during the day, but now they are failing again somewhere else.

**Comment by Barthelemy** [comment]
I don't even find where it is failing... Could it be the same as in https://github.com/AliceO2Group/QualityControl/pull/589#issuecomment-764744483 ? @TimoWilken @ktf any idea ?

**Comment by davidrohr** [comment]
Now all CIs are failing without any indication what is going wrong @Barthelemy @TimoWilken

**Comment by Barthelemy** [comment]
@ktf @TimoWilken Could you check ?

**Comment by davidrohr** [comment]
@Barthelemy : It is finally green :)
Could you merge it?

**Pull request merged**
