### PR TITLE
ZDC: Task reconstruction First Version

### PR DESCRIPTION
**Pull request by cpuggion84**
The ZDCRecDataTask show the reconstruction histograms.
1D Histogrmas:
- 26 ADC Energy
- 10 TDC Time
- 10 TDC Amplitude
2D Histograms
-  4 ADCSum vs ADC Central Tower
- 10 ADC vs TDC Time 
-   1 TDC Time ZNC - ZNA vs TDC  Time ZNC + ZNA
- 10 TDC  TDC amplitude vs TDC Time

### CODE REVIEW

**Comment by cpuggion84** [comment]
I saw that the  pull request showed several errors in the tests.
Do these errors depend on the code I wrote? Can I do something to correct them?

These days I made the following changes to the task:
- the task read some parameters from the .json file about bin of histograms.
- fixed some bugs when fill the histograms 1D TDC . 
Can I commit these changes in this pull request?
The commissioning of the ZDC will begin on September 19th. Would it be possible to have the code installed on P2 before this date?
Thank you 
Carlo

**Comment by Barthelemy** [comment]
Dear Carlo, 

It is better not to add more commits to this PR if they are not directly related to the existing ones. The errors over the weekend were spurrious due to the ccdb-test being down. The only real error is the one on macOS that you should fix and commit in this PR. 

Cheers

**Comment by cpuggion84** [comment]
Dear Barth,
Thank you for your replay.
I have seen the details of the error.
"o2::zdc::RecEventFlat::next()", referenced from:
      o2::quality_control_modules::zdc::ZDCRecDataTask::process(gsl::span<o2::zdc::BCRecData const, 18446744073709551615ul> const&, gsl::span<o2::zdc::ZDCEnergy const, 18446744073709551615ul> const&, gsl::span<o2::zdc::ZDCTDCData const, 18446744073709551615ul> const&, gsl::span<unsigned short const, 18446744073709551615ul> const&) in ZDCRecDataTask.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I had a similar problem on centos s8. I  send you an email you about this on July 11th.
Then luckily it was fixed when I reinstalled O2 and O2 Suite on August 5th.
When I reinstalled O2 and O2 Suite on July 22, the error was still present.
Now I don't have the possibility to test QC on macOs.
Do you have any suggestions about this error?

I'll make a new pull request with the changes I wrote about in the previous comment.

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
tested the mac build locally

**Comment by cpuggion84** [comment]
thank you very much for your help

**Pull request merged**
