### PR TITLE
Adding plots to ITSTPC matching QC

### PR DESCRIPTION
**Pull request by chiarazampolli**
Goes with https://github.com/AliceO2Group/AliceO2/pull/11974. 
To test:
o2-global-track-cluster-reader --tpc-track-reader "tpctracks.root --reader-delay 10" --shm-segment-size 64000000000 --disable-mc --hbfutils-config o2_tfidinfo.root --track-types "ITS,TPC,ITS-TPC" --cluster-types "TPC,ITS" | o2-qc --config json:///home/zampolli/work/O2/RelVal/CPU_6/QC_GLO.json -b
(json attached in a comment below).

### CODE REVIEW

**Comment by Barthelemy** [comment]
waiting for https://github.com/AliceO2Group/AliceO2/pull/11974 to be merged then. 

Please check the formatting issues.

**Comment by chiarazampolli** [comment]
Yes, i will fix everything, including updating json.

**Comment by chiarazampolli** [comment]
Moving to WIP while I fix the formatting etc.

**Comment by chiarazampolli** [comment]
Not all jsons were tested. But I add here the one I did test, for data (extension is txt to be able to upload it here):
[QC_GLO.txt](https://github.com/AliceO2Group/QualityControl/files/12754225/QC_GLO.txt)

**Review by knopers8 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @knopers8 , 
I think the error is not related to this PR... Maybe we can merge it?
Cheers,
Chiara

**Comment by chiarazampolli** [comment]
Ciao @knopers8 , 
No, I did not compile on mac. But the compilation for the PR in O2 worked. I don't know why.
If you check the changes, it is just replacing some getters with others, maybe we can merge? I don't know otherwise.
Cheers,
Chiara

**Comment by knopers8** [comment]
The O2 check failed in a test, the build itself went fine actually. Anyway, I agree that we should not expect any surprises here. Usually the mac builds expose some implicit type conversions, but `matchType::SIZE` is `int`, so are your indexes in for loops and `get*` functions, so this should be fine.

I will force-merge and draft a release.

**Comment by chiarazampolli** [comment]
Thanks!! Fingers crossed that all works fine :)

**Pull request merged**
