### PR TITLE
Always using TPC tracks to fill histograms and bug fix

### PR DESCRIPTION
**Pull request by chiarazampolli**
@noferini : I have not yet tested the effect of this change locally, but it should be the correct way to do.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @Barthelemy , 

I cannot find the relevant error in the o2 built, and the one for macOS is unrelated. This PR is needed for the async pass, could you take a look?

Thanks!

Chiara

**Comment by knopers8** [comment]
@ktf @TimoWilken @MichaelLettrich O2 build seems to "successfully fail" while the macOS one fails with:
```
CMake Error at /System/Volumes/Data/build/ci_checks/alice_ci_0/qualitycontrol-o2/sw/BUILD/f36ce76dfc29bc3106d4625ee1080438dd352065/ROOT/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-RELWITHDEBINFO.cmake:49 (message):
  Command failed: 2

   '/usr/local/bin/gmake'

  See also

    /System/Volumes/Data/build/ci_checks/alice_ci_0/qualitycontrol-o2/sw/BUILD/f36ce76dfc29bc3106d4625ee1080438dd352065/ROOT/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-*.log
```
Could you please have a look?

**Comment by chiarazampolli** [comment]
Please, do not merge yet.

**Comment by chiarazampolli** [comment]
PR ready to be merged from my side (if approved).

**Comment by chiarazampolli** [comment]
Hi @davidrohr , 

Can we have this merged? The failure in O2 is for sure unrelated. 
Then we can have it in tonight's nightly, and I can try on the grid. It is the last test I want to make before giving everything to Catalin for central async reco.

Chiara

**Comment by chiarazampolli** [comment]
MacOS failure not related, if there is nothing against it, I would ask that the PR is merged to enter the earliest nightly to be then used for the final test before the central async reco.

Chiara

**Pull request merged**
