### PR TITLE
Adapt to changes in DPL ServiceSpec API

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy The fix on master was missing one... Could you tag again?

**Comment by Barthelemy** [comment]
There is something wrong with the CI

**Comment by knopers8** [comment]
It seems like it reacts only to PRs to master.

**Comment by Barthelemy** [comment]
@ktf So it is ok on master (from what I see) but not in v0.26.3 ?
@knopers8 indeed

--> I am going to make the same change as the one propose in this PR on top of v0.26.3 and tag v0.26.4

**Comment by Barthelemy** [comment]
Ok, it is here : https://github.com/AliceO2Group/QualityControl/tree/v0.26.4

**Pull request closed without merging**
