### PR TITLE
[O2-2018] No need to link to ms_gsl...

### PR DESCRIPTION
**Pull request by aphecetche**
... which is to be renamed to Microsoft.GSL::GSL anyway

### CODE REVIEW

**Comment by aphecetche** [comment]
For the record, this one is needed by https://github.com/AliceO2Group/AliceO2/pull/6075

**Comment by aphecetche** [comment]
@TimoWilken any idea what are the timeout failures for build/QualityControl/o2 ?

**Comment by TimoWilken** [comment]
I don't know, sorry. I've restarted it for now, let me know if that doesn't fix it.

**Comment by aphecetche** [comment]
@TimoWilken the error is unfortunately still present. @Barthelemy maybe this is something you've already observed ?

**Comment by aphecetche** [comment]
@TimoWilken @Barthelemy don't know what changed but now it's green, ready to be merged 😄

**Comment by Barthelemy** [comment]
I am not sure but it feels like it is an issue with the compiler version and the c++ standard version in Common. @ktf what do you think ?

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
It is this PR that was merged although `o2-dataflow` was red: https://github.com/AliceO2Group/AliceO2/pull/6102

**Comment by shahor02** [comment]
sorry for that, I think the dataflow in the original PR was green at some stage, then I had some incremental changes in other files. The boost::fs was creating problems, so the change is needed. 
@ktf do you understand why in some cases it fails to find the header?

**Comment by Barthelemy** [comment]
`o2-dataflow` is broken until we move to gcc10, ignoring the check failure. 
See https://github.com/AliceO2Group/AliceO2/pull/6102

**Pull request merged**
