### PR TITLE
MCH: improve preclusters task

### PR DESCRIPTION
**Pull request by aferrero2707**
This PR introduces several improvement to the analysis of pre-clusters:
- improved selection of pre-clusters for efficiency analysis
- added plots with number of pre-clusters per TF
- added plots with mean efficiency per detection element
- added efficiency plot in electronics coordinates
- improved beautify method in checker
- added mergeable TH1 ratio class

### CODE REVIEW

**Comment by aferrero2707** [comment]
@Barthelemy @knopers8 the o2 and macOS builds seem to fail for reasons un-related to this PR. Would it be possible to review and eventually merge nevertheless, or should I re-trigger the CI builds?

Thanks!

**Comment by Barthelemy** [comment]
we merge !

**Comment by Barthelemy** [comment]
No other review needed ?

**Comment by aferrero2707** [comment]
@aphecetche would you like to have a look?

**Comment by aferrero2707** [comment]
@Barthelemy @knopers8 we can merge this one. Thanks!

**Pull request merged**
