### PR TITLE
[WIP] Changes to be compatible with ROOT 6.18 (QC-192)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Thanks @pzhristov

**Comment by knopers8** [comment]
Don't forget about `Modules/Skeleton/.CMakeListsEmpty.txt`, it is the one that is used as a template for modules-configurator

**Comment by Barthelemy** [comment]
@knopers8 good point !
I am checking it.

**Comment by Barthelemy** [comment]
After the update of CMake no changes are needed any more.

**Pull request closed without merging**
