### PR TITLE
Mid

### PR DESCRIPTION
**Pull request by gtaillepied**
MID: added raw data checker in RawQcTask

### CODE REVIEW

**Comment by dstocco** [comment]
I might be wrong, but I'd say that the compilation errors are unrelated with the PR.
@Barthelemy : I see that no reviewer is assigned. Should be checked by you or Laurent before merging?

**Comment by Barthelemy** [comment]
I will review it today

**Comment by Barthelemy** [comment]
errors are unrelated, merging

**Comment by dstocco** [comment]
Thanks!

**Comment by gtaillepied** [comment]
Thanks a lot!

**Pull request merged**
