### PR TITLE
other improvement for TOF QC trending

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
@ercolessi @njacazio 
I already open a new PR to avoid to integrate in the full run in the trending plot.
Still WIP

**Review by njacazio — APPROVED** [review]
Great, thanks!

**Comment by noferini** [comment]
Hi,
I guess macOS error is not related to this PR

ld: library not found for -lcrypto.44
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by njacazio** [comment]
@knopers8 @Barthelemy could you merge this ? the CI seems unrelated

**Pull request merged**
