### PR TITLE
Consistent path structure in QCDB (QC-360)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
depends on #445

**Comment by Fakerr** [comment]
Hey there, just curious here. Since this PR depends on another, would you be interested by a [github app](https://github.com/marketplace/dpulls) that prevents a PR from being merged until its dependency is itself merged ? cc @Barthelemy

**Comment by Barthelemy** [comment]
The commits are a bit of a mess due to the dependency on another, now merged, PR. However the changes are ok and I will squash before merging.

**Comment by Barthelemy** [comment]
todo: also make sure it works for external devices.

**Comment by knopers8** [comment]
Thanks!

**Review by knopers8 — APPROVED** [review]

**Comment by Barthelemy** [comment]
Concerning the external tasks, there is a bug unrelated to this PR. Thus I will merge and I will then work on the bug in a different PR.

**Pull request merged**
