### PR TITLE
MFT: new MC Track Task

### PR DESCRIPTION
**Pull request by Edingrast**

### CODE REVIEW

**Comment by Barthelemy** [comment]
I think that you have a typo `QCMFTTrackMCTask` -> `QcMFTTrackMCTask` that breaks the checks.

**Comment by Edingrast** [comment]
> I think that you have a typo `QCMFTTrackMCTask` -> `QcMFTTrackMCTask` that breaks the checks.

Hi Barth,
Thank you for your comment. The issue has been fixed.
Sara

**Comment by diana0x0f** [comment]
Hi @Barthelemy ,
one of the checks (`o2-cs8`) is still not successful and it is not clear to us what could be the cause. Could you please have a look? Thanks!

**Comment by Barthelemy** [comment]
this is a spurrious error, i will merge your commit.

**Pull request merged**
