### PR TITLE
HMPID_NewDigitStructure

### PR DESCRIPTION
**Pull request by fapfap69**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
Accepting, but let's see what the CI says (as a first-time contributor, your PR would not be checked before being accepted).

**Comment by fapfap69** [comment]
> Accepting, but let's see what the CI says (as a first-time contributor, your PR would not be checked before being accepted).

Hi Piotr,
I experienced some problems with includes.
In this version we moved some source files in O2/Detectors and O2/DataFormats.
The compilation, on my MAC Installation works fine ! 
But fails in the PR check :(

I'd try to modify the Cmake file in order to target this includes, with no positive results.
Please could you indicate to my, references to how set the CMakefiles to target O2 includes, external to the QC ?

Thanks a lot

**Comment by knopers8** [comment]
@fapfap69 Just a quick question before we investigate it deeper. Don't you need https://github.com/AliceO2Group/AliceO2/pull/5795 merged first to make this PR here compile? In our checks we compile PRs against O2@dev.

**Comment by fapfap69** [comment]
> @fapfap69 Just a quick question before we investigate it deeper. Don't you need [AliceO2Group/AliceO2#5795](https://github.com/AliceO2Group/AliceO2/pull/5795) merged first to make this PR here compile? In our checks we compile PRs against O2@dev.

Ya. you are right ! I'm really stupid :)
Thanks a lot !!

**Comment by gvolpe79** [comment]
Hi Piotr,
it seems that now the compilation is giving error not on the HMPID code, right?!

**Comment by knopers8** [comment]
Yes, this is a general problem in the CI and has been reported to the admins ( https://alice.its.cern.ch/jira/browse/O2-2214 ). However, the build fails before it reaches the HMPID code in QC, so we cannot know if it compiles now correctly.

**Comment by knopers8** [comment]
The o2 build shows the usual Logger errors, but I will force merge, since the other two builds are passing.

**Pull request merged**
