### PR TITLE
TPC: Fix bug in masking in CheckOfSlices

### PR DESCRIPTION
**Pull request by mlesch**

### CODE REVIEW

**Review by wiechula — APPROVED** [review]

**Comment by Barthelemy** [comment]
@ktf 
build/QualityControl/o2-dataflow/macOS-arm is stuck. Could you have a look please ? d

**Comment by ktf** [comment]
Looks like the whole cluster is having troubles....

**Comment by ktf** [comment]
Should be back in business.

**Comment by Barthelemy** [comment]
@ktf Thank you

**Pull request merged**
