### PR TITLE
[EMCAL-524] Prototype QC component for EMCAL digits

### PR DESCRIPTION
**Pull request by mfasDa**
Digits component monitoring digit amplitude and time
for each tower separately. Creating also the EMCAL
module.

In order to run the Digits QC task a separate workflow
(qcRunEmcalDigit) is used. The data source is an
EMCAL publisher implemented in the O2 EMCAL reco
workflow supporting only digits for the moment. The
QC task are initialized using the standard method
via a configuration file.

### CODE REVIEW

**Comment by mfasDa** [comment]
Work in progress - don't merge. Depending on https://github.com/AliceO2Group/AliceO2/pull/2099.

**Comment by mfasDa** [comment]
There is a problem from the cmake transition that needs to be sorted out first: Due to implicit dependencies the component needs $O2_ROOT/include/GPU in addition to $O2_ROOT/include in the include path (needed by o2::CommonDataFormats::TimeStamp, dependency of o2::emcal::Digit). Currently this is circumvented using a hack in the CMakeLists.txt of the EMCAL module.

**Comment by mfasDa** [comment]
WIP check can be removed since emcal-recoworkflow is merged in O2.

**Comment by mfasDa** [comment]
@Barthelemy From my side ready - please merge if appropriate!

**Comment by Barthelemy** [comment]
I will review it tomorrow and let you know. Thank you for the nice work !

**Comment by mfasDa** [comment]
Hi @Barthelemy, 

this is just the first EMCAL task monitoring at digits level - should be straight forward to merge. I would prefer having this merged in order not share the code for a long period on a development branch, because this requires a lot of rebasing. The issue with the core library I didn't yet touch and is not in this commit.

Cheers

Markus

**Comment by Barthelemy** [comment]
Hi Markus, 
I understand. I have read the code and it is indeed simple and pretty straightforward. I will merge it. The test failures are unrelated. 
Cheers,

**Pull request merged**
