### PR TITLE
[QC-1033] Aggregators: OnAnyNonZero: failure to use with checks producing single QO

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
you could consider adding a test case for this

**Comment by Barthelemy** [comment]
I added a test and reformatted.

**Comment by aferrero2707** [comment]
I confirm the CI error messages also in a local build. The compiler seems to be confused between `Catch::cout` and `std::cout`:
```
/home/flp/Workflows/Software/alice/sw/SOURCES/QualityControl/barth-quick-fix-aggregators-onAnyNonZero/0/Framework/test/testAggregatorRunner.cxx: In function 'void CATCH2_INTERNAL_TEST_4()':
/home/flp/Workflows/Software/alice/sw/SOURCES/QualityControl/barth-quick-fix-aggregators-onAnyNonZero/0/Framework/test/testAggregatorRunner.cxx:103:5: error: 'cout' was not declared in this scope; did you mean 'Catch::cout'?
  103 |     cout << "- " << x.name << endl;
      |     ^~~~
      |     Catch::cout
In file included from /home/flp/Workflows/Software/alice/sw/SOURCES/QualityControl/barth-quick-fix-aggregators-onAnyNonZero/0/Framework/test/testAggregatorRunner.cxx:29:
/home/flp/Workflows/Software/alice/sw/slc7_x86-64/O2/upstream-dev-1/include/catch_amalgamated.hpp:9651:19: note: 'Catch::cout' declared here
 9651 |     std::ostream& cout();
      |                   ^~~~
```

**Comment by Barthelemy** [comment]
fixed hopefully

**Review by knopers8 — APPROVED** [review]

**Pull request merged**
