### PR TITLE
MFT: plots for cluster size in pixels

### PR DESCRIPTION
**Pull request by diana0x0f**
Adding histograms for cluster size in pixels, separately for normal (frequent) cluster shapes and for grouped clusters.

### CODE REVIEW

**Comment by knopers8** [comment]
The failure of FST seems legit:
```
reco_NOGPU.log:[2661:qc-task-MFT-QcMFTClusterTask]: [05:59:26][ERROR] Exception caught: Unknown argument requested patterns - no matching route found for patterns 
reco_NOGPU.log-[2661:qc-task-MFT-QcMFTClusterTask]:     /sw/slc7_x86-64/QualityControl/1359-slc7_x86-64-local2/lib/libO2QcMFT.so: decltype(auto) o2::framework::InputRecord::get<gsl::span<unsigned char, 18446744073709551615ul>, char const*>(char const*, int) const
reco_NOGPU.log-[2661:qc-task-MFT-QcMFTClusterTask]:     /sw/slc7_x86-64/QualityControl/1359-slc7_x86-64-local2/lib/libO2QcMFT.so: o2::quality_control_modules::mft::QcMFTClusterTask::monitorData(o2::framework::ProcessingContext&)
```

**Comment by diana0x0f** [comment]
Hi @knopers8 ,
the query is defined in `qc-mft-cluster.json`, the patterns branch is filled in the `runMFTClustersRootFileReader.cxx` file, it follows the same structure as the rest. It runs with no errors on my machine. What else could be there that prevents it from successfully running? thanks

**Comment by tomas-herman** [comment]
Hi @knopers8, perhaps some more info that could help understand the issue. The use of the patterns that we are implementing in this PR is already in production by ITS without issues, e.g.: https://github.com/AliceO2Group/QualityControl/blob/41f4b2bc1776a2bca6346547719f95826575f589/Modules/ITS/src/ITSClusterTask.cxx#L150
The pattern object is defined here: https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h respectively here: https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterPattern.h

**Comment by knopers8** [comment]
hm, perhaps the config file for the FST does not request "patterns"? I am not 100% sure, but I think this is the file it is using:
https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/qc-sync/mft.json

**Comment by tomas-herman** [comment]
Hi @knopers8, this json file was not updated for quite some time so if it is being used for the check I understand why it fails. Is this a new check? I am surprised we did not have this issue sooner.

I have created a PR with the latest update: https://github.com/AliceO2Group/O2DPG/pull/551

Once it is merged the test should go ok?

**Comment by knopers8** [comment]
If this is indeed the json file which is used there, it should stop failing, but as I said, I am not sure myself if this is the one, as I don't take care of those full system tests.

**Review by tomas-herman — APPROVED** [review]

**Comment by tomas-herman** [comment]
With this fix it should finally work: https://github.com/AliceO2Group/O2DPG/pull/555

**Pull request merged**
