### PR TITLE
QC-466 - Survive getting an RDH with version < 6.

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]

**Comment by Barthelemy** [comment]
@TimoWilken @ktf Is there a problem with these builds ? they are still orange after the weekend.

**Comment by TimoWilken** [comment]
@Barthelemy looking into it.

**Comment by TimoWilken** [comment]
@Barthelemy sorry, the builder was stuck. It has a queue of 3 PRs now.

**Comment by Barthelemy** [comment]
Thank you ! would there be a way to monitor this  and take actions automatically ?

**Comment by TimoWilken** [comment]
@Barthelemy Probably, though my to-do list is quite full at the moment :)

This was actually a problem that was fixed by alisw/ali-bot#826, but this particular worker must've slipped through when I checked which ones were stuck last week. Fixed now.

**Comment by TimoWilken** [comment]
@Barthelemy all checks passed now (though build/QualityControl/o2 has some warnings), sorry for the delay.

**Comment by Barthelemy** [comment]
Thanks !

**Pull request merged**
