### PR TITLE
TRD further code cleanup

### PR DESCRIPTION
**Pull request by martenole**
Hi @deependra170598 and @maroozm and @nasirmehdimalik 
please take a look if I have removed anything in this PR that might eventually be used. I think not, but better if you double-check of course. The fit of the PH plot is now done in O2 in the T0 calibration. Many classes were obsolete as far as I can tell.
The TRDQC.json I would like to keep for us to do local tests. It works with some local reconstruction from CTF files. But from the postprocessing I don't see if it is done at all or not. But also not sure if it is supposed when run locally. @deependra170598 do you know?

### CODE REVIEW

**Comment by maroozm** [comment]
Hi @martenole ,
   Everything seems fine from my side.
Thanks,
Salman

**Comment by Barthelemy** [comment]
@martenole do you want more approvals from your side before I merge ?

**Comment by deependra170598** [comment]
Yes @martenole ,there is no setting for postprocessing in TRDQC.json till now. So if we want local postprocessing we have to update it. 
Regarding generating trend for t0 peak position and its chi2 value trend of fit, this job was done by TRDReductor.cxx. As you said fit is done in O2, so I have to look at how I can find trends from there.

**Comment by deependra170598** [comment]
Hi @martenole , TRDQC.json contains examples of postprocessing settings for generating trends for tracklet mean etc and summerising Quality of checks. These settings were used by me for local testing and also in staging. After last PR by me on trackletCountCheck, I need to verify these settings again.

TRDReductor.cxx was responsible for generating t0peak position trend and chi2 trend of fit. As you said it is now done in O2 t0 calibration, I have to look at how can I find trend from there. Thanks.

**Comment by martenole** [comment]
This is ready to be merged :+1:

**Pull request merged**
