### PR TITLE
fix for selection and denominator for efficiency

### PR DESCRIPTION
**Pull request by chiarazampolli**
@noferini , FYI.

### CODE REVIEW

**Comment by noferini** [comment]
I would change the default of eta cut to 0.8

diff --git a/Modules/TOF/include/TOF/TOFMatchedTracks.h b/Modules/TOF/include/TOF/TOFMatchedTracks.h
index 3cba08e81e..def7a0192e 100644
--- a/Modules/TOF/include/TOF/TOFMatchedTracks.h
+++ b/Modules/TOF/include/TOF/TOFMatchedTracks.h
@@ -94,7 +94,7 @@ class TOFMatchedTracks final : public TaskInterface
 
   // for track selection
   float mPtCut = 0.1f;
-  float mEtaCut = 1.4f;
+  float mEtaCut = 0.8f;
   int32_t mNTPCClustersCut = 40;
   float mDCACut = 100.f;
   float mDCACutY = 10.f;

**Comment by chiarazampolli** [comment]
Ciao @noferini , 

Done!

Chiara

**Comment by noferini** [comment]
if (auto param = mCustomParameters.find("EtaCut"); param != mCustomParameters.end()) {

  if (auto param = mCustomParameters.find("etaCut"); param != mCustomParameters.end()) {

"EtaCut" -> "etaCut" otherwise change it in the json

**Comment by chiarazampolli** [comment]
Good catch, @noferini !

**Comment by noferini** [comment]
Last comment (I hope)
I can run with "ITS-TPC,TPC" json but not with "ITS-TPC" one.
This because now TPC tracks are used also in the case of global track, then also the TPC only track input is required.
ITS-TPC json should be fixed.

**Comment by chiarazampolli** [comment]
Very useful again! Done (I tested it and it worked, but please check as well).

**Comment by chiarazampolli** [comment]
Failure on macos seems not related to the PR, @Barthelemy , can you check?

**Comment by Barthelemy** [comment]
@TimoWilken The macos build is still failing

@chiarazampolli I am force merging

**Comment by TimoWilken** [comment]
@Barthelemy sorry, I missed that the `o2` defaults also override the XRootD version. Fixed in https://github.com/alisw/alidist/pull/3537.

**Pull request merged**
