### PR TITLE
[QC-968] Use BasicCCDBManager instead of ccdbApi

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
I still have to test it.

**Comment by Barthelemy** [comment]
tested

**Comment by knopers8** [comment]
it seems it breaks with a CPV task:
```
[56801:qc-task-CPV-PhysicsOnEPNs]: *** Error in `o2-qc': free(): invalid pointer: 0x000000000bb597c0 ***
[56801:qc-task-CPV-PhysicsOnEPNs]: ======= Backtrace: =========
[56801:qc-task-CPV-PhysicsOnEPNs]: /lib64/libc.so.6(+0x81329)[0x7f56484be329]
[56801:qc-task-CPV-PhysicsOnEPNs]: /sw/slc7_x86-64/QualityControl/1838-slc7_x86-64-local5/lib/libO2QualityControl.so(_ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_N2o24ccdb19CCDBManagerInstance12CachedObjectEESaISC_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSE_18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyENSE_17_Hashtable_traitsILb1ELb0ELb1EEEE5clearEv+0x113)[0x7f5656effa73]
[56801:qc-task-CPV-PhysicsOnEPNs]: /sw/slc7_x86-64/QualityControl/1838-slc7_x86-64-local5/lib/libO2QualityControl.so(_ZN2o24ccdb16BasicCCDBManagerD1Ev+0x83)[0x7f5656f00373]
[56801:qc-task-CPV-PhysicsOnEPNs]: /lib64/libc.so.6(+0x39ce9)[0x7f5648476ce9]
[56801:qc-task-CPV-PhysicsOnEPNs]: /lib64/libc.so.6(+0x39d37)[0x7f5648476d37]
[56801:qc-task-CPV-PhysicsOnEPNs]: /lib64/libc.so.6(__libc_start_main+0xfc)[0x7f564845f55c]
[56801:qc-task-CPV-PhysicsOnEPNs]: o2-qc[0x41b0ff]
```

**Comment by Barthelemy** [comment]
ok, indeed, I'll have a look

**Comment by shahor02** [comment]
Hi @Barthelemy 
I think in https://github.com/AliceO2Group/QualityControl/blob/26e4e7b620e45d3a574b948960f9e3816edccd1c/Modules/CPV/src/PhysicsTask.cxx#L288 and a few lines below the objects fetched from the CCDB are deleted, therefore invalidating the pointers in the BasicCCDBManager cache.

**Comment by Barthelemy** [comment]
ah, I see. The BasicCCDBManager owns the objects it fetches, right ? 
I am removing the deletion then.

**Comment by shahor02** [comment]
Yes, unless the caching was explicitly suppressed via `BasicCCDBManager::instance().setCaching(false);`

**Comment by sevdokim** [comment]
Hi @Barthelemy 
indeed I access ccdb objects using DPL fetcher, see for example 
https://ali-consul-ui.cern.ch/ui/alice-o2-cluster/kv/o2/components/qc/ANY/any/cpv-physics-qcmn-epn/edit
The possibility to access objects via ccdbApi was there for the case when task is not subscribed for corresponding inputs. 
I think your changes are good with BasicCCDBManager which owns objects. Do I understand correctly that it will delete objects only when workflow finished?

**Comment by shahor02** [comment]
@sevdokim both BasicCCDBManager and DPL fetcher are caching objects therefore they should be never deleted by the user. 
The caches are cleaned internally on exit.

**Comment by Barthelemy** [comment]
ready for review

**Review by knopers8 — APPROVED** [review]

**Pull request merged**
