### PR TITLE
[EMCAL-526] Remove leftover debug statements from previous investigation

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Removing leftover warnings introduced in #800

**Comment by knopers8** [comment]
CI errors are genuine.

**Comment by mfasDa** [comment]
Sorry, overlooked - line became obsolete with removed debug message

**Comment by mfasDa** [comment]
@knopers8 could you please merge? The mac errors are again unrelared

**Pull request merged**
