### PR TITLE
TPC CalDetPublisher: fetch CalPad in std::unordered_map from CCDB + add…

### PR DESCRIPTION
**Pull request by tklemenz**
… ZS calibration file check

### CODE REVIEW

**Comment by tklemenz** [comment]
This needs [this PR in O2](https://github.com/AliceO2Group/AliceO2/pull/6531) to have the templated `getCalPad` function.

**Comment by Barthelemy** [comment]
It seems that there is a problem with circular changes here. This PR depends on another PR in O2 which depends on this one. 

One option is to force merge on both sides and prepare a new QC version quickly to avoid breaking every PR on O2 and having an unstable master in QC. 

Another option, is to make the change backward compatible. In the specific case, you could keep the old methods (`getCalPad`,  but mark them as deprecated. This way, you can merge the PR in O2 and then the one in QC. 

I prefer the second one but understand that it is more work for you as you have to remove the methods in another iteration.

**Comment by tklemenz** [comment]
Hi Barth, I just discussed with Jens already that I will make a few changes to make it backward compatible.

**Comment by Barthelemy** [comment]
thank you

**Comment by tklemenz** [comment]
@Barthelemy The PR in O2 was just merged. Will the tests rerun on their own or do they need to be triggered?

**Comment by Barthelemy** [comment]
They restart occasionally

**Comment by Barthelemy** [comment]
alidoctor error in mac unrelated, merging.

**Pull request merged**
