### PR TITLE
[QC-463] Daqtask only publish included det

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
Thanks! The code will grow in a bit ugly way if the number of histogram kinds grows, but we can address that later.

**Comment by Barthelemy** [comment]
I agree on the fact that it should be rewritten when the number of plots grows.

**Comment by knopers8** [comment]
We could have some kind of extended map, which automatically creates and registers histograms if you try to access a new key.

**Comment by Barthelemy** [comment]
yes

**Pull request merged**
