### PR TITLE
[WIP] TPC: add occupancy plot to Cluster task

### PR DESCRIPTION
**Pull request by tklemenz**

### CODE REVIEW

**Comment by tklemenz** [comment]
This needs https://github.com/AliceO2Group/AliceO2/pull/10658.

**Review by wiechula — COMMENTED** [review]
Looks ok so far. I guess we need to wait for the PR in O2.

**Comment by Barthelemy** [comment]
@wiechula what should we do with this PR ? do you want to fix the conflict and we merge ?

**Comment by wiechula** [comment]
@Barthelemy , it seems the O2 dependency was not merged, I'll check with @tklemenz .

**Comment by tklemenz** [comment]
Exactly, the O2 dependency is missing, so merging now probably doesn't make much sense. I won't be in the office for a while but I'll move the task on someone else. So maybe it's the best if we close this PR opened by me and the one finishing the task re-opens.

**Pull request closed without merging**
