### PR TITLE
o2-data-dump: use AliceO2::DebugGUI

### PR DESCRIPTION
**Pull request by ktf**
This replaces the internal version with the common one, so that we
can merge https://github.com/alisw/alidist/pull/2728 with the Metal
support.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy could you it give a try? I got it to compile just fine, but I've not had chance to try it out. It will also speed up the build a bit, I guess.

**Comment by Barthelemy** [comment]
@ktf ok, compiling on CC7 . Thank you

**Review by Barthelemy — APPROVED** [review]
tested and working on mac

**Comment by Barthelemy** [comment]
-42000 lines is always something :)

**Comment by ktf** [comment]
cool thanks!

**Pull request merged**
