### PR TITLE
[QC-736] Set the facility after other flags are set

### PR DESCRIPTION
**Pull request by Barthelemy**
@davidrohr

### CODE REVIEW

**Comment by davidrohr** [comment]
thx!

**Comment by davidrohr** [comment]
Unfortunately, I have no easy way to test it without having an RPM build and installing that on the EPNs.
But the fix looks so trivial, that I am 99.9% sure it is correct.
Could we have a new QC tag with this?

**Comment by Barthelemy** [comment]
Sure we can, I will release a patch version.

**Comment by Barthelemy** [comment]
Here is the patch version: https://github.com/AliceO2Group/QualityControl/releases/tag/v1.45.1
And the pr in alidist: https://github.com/alisw/alidist/pull/3797

**Pull request merged**
